// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const airtable = Object.freeze({
  base_create(filter?: WebhookFilter) {
    return providerTrigger("airtable", "base.create", filter);
  },
  base_delete(filter?: WebhookFilter) {
    return providerTrigger("airtable", "base.delete", filter);
  },
  base_update(filter?: WebhookFilter) {
    return providerTrigger("airtable", "base.update", filter);
  },
  record_create(filter?: WebhookFilter) {
    return providerTrigger("airtable", "record.create", filter);
  },
  record_delete(filter?: WebhookFilter) {
    return providerTrigger("airtable", "record.delete", filter);
  },
  record_update(filter?: WebhookFilter) {
    return providerTrigger("airtable", "record.update", filter);
  },
  table_create(filter?: WebhookFilter) {
    return providerTrigger("airtable", "table.create", filter);
  },
  table_delete(filter?: WebhookFilter) {
    return providerTrigger("airtable", "table.delete", filter);
  },
  table_update(filter?: WebhookFilter) {
    return providerTrigger("airtable", "table.update", filter);
  },
});
