// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const asana = Object.freeze({
  project_added(filter?: WebhookFilter) {
    return providerTrigger("asana", "project.added", filter);
  },
  project_changed(filter?: WebhookFilter) {
    return providerTrigger("asana", "project.changed", filter);
  },
  project_deleted(filter?: WebhookFilter) {
    return providerTrigger("asana", "project.deleted", filter);
  },
  project_removed(filter?: WebhookFilter) {
    return providerTrigger("asana", "project.removed", filter);
  },
  section_added(filter?: WebhookFilter) {
    return providerTrigger("asana", "section.added", filter);
  },
  section_changed(filter?: WebhookFilter) {
    return providerTrigger("asana", "section.changed", filter);
  },
  section_deleted(filter?: WebhookFilter) {
    return providerTrigger("asana", "section.deleted", filter);
  },
  section_removed(filter?: WebhookFilter) {
    return providerTrigger("asana", "section.removed", filter);
  },
  task_added(filter?: WebhookFilter) {
    return providerTrigger("asana", "task.added", filter);
  },
  task_changed(filter?: WebhookFilter) {
    return providerTrigger("asana", "task.changed", filter);
  },
  task_completed(filter?: WebhookFilter) {
    return providerTrigger("asana", "task.completed", filter);
  },
  task_deleted(filter?: WebhookFilter) {
    return providerTrigger("asana", "task.deleted", filter);
  },
  task_removed(filter?: WebhookFilter) {
    return providerTrigger("asana", "task.removed", filter);
  },
  workspace_added(filter?: WebhookFilter) {
    return providerTrigger("asana", "workspace.added", filter);
  },
  workspace_changed(filter?: WebhookFilter) {
    return providerTrigger("asana", "workspace.changed", filter);
  },
  workspace_deleted(filter?: WebhookFilter) {
    return providerTrigger("asana", "workspace.deleted", filter);
  },
  workspace_removed(filter?: WebhookFilter) {
    return providerTrigger("asana", "workspace.removed", filter);
  },
});
