// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const box = Object.freeze({
  file_created(filter?: WebhookFilter) {
    return providerTrigger("box", "file.created", filter);
  },
  file_deleted(filter?: WebhookFilter) {
    return providerTrigger("box", "file.deleted", filter);
  },
  file_updated(filter?: WebhookFilter) {
    return providerTrigger("box", "file.updated", filter);
  },
});
