// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const calendly = Object.freeze({
  event_type_canceled(filter?: WebhookFilter) {
    return providerTrigger("calendly", "event_type.canceled", filter);
  },
  event_type_created(filter?: WebhookFilter) {
    return providerTrigger("calendly", "event_type.created", filter);
  },
  event_type_deleted(filter?: WebhookFilter) {
    return providerTrigger("calendly", "event_type.deleted", filter);
  },
  event_type_updated(filter?: WebhookFilter) {
    return providerTrigger("calendly", "event_type.updated", filter);
  },
  invitee_canceled(filter?: WebhookFilter) {
    return providerTrigger("calendly", "invitee.canceled", filter);
  },
  invitee_created(filter?: WebhookFilter) {
    return providerTrigger("calendly", "invitee.created", filter);
  },
  invitee_deleted(filter?: WebhookFilter) {
    return providerTrigger("calendly", "invitee.deleted", filter);
  },
  invitee_updated(filter?: WebhookFilter) {
    return providerTrigger("calendly", "invitee.updated", filter);
  },
  scheduled_event_canceled(filter?: WebhookFilter) {
    return providerTrigger("calendly", "scheduled_event.canceled", filter);
  },
  scheduled_event_created(filter?: WebhookFilter) {
    return providerTrigger("calendly", "scheduled_event.created", filter);
  },
  scheduled_event_deleted(filter?: WebhookFilter) {
    return providerTrigger("calendly", "scheduled_event.deleted", filter);
  },
  scheduled_event_updated(filter?: WebhookFilter) {
    return providerTrigger("calendly", "scheduled_event.updated", filter);
  },
});
