// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const clickup = Object.freeze({
  folder_created(filter?: WebhookFilter) {
    return providerTrigger("clickup", "folder.created", filter);
  },
  folder_deleted(filter?: WebhookFilter) {
    return providerTrigger("clickup", "folder.deleted", filter);
  },
  folder_updated(filter?: WebhookFilter) {
    return providerTrigger("clickup", "folder.updated", filter);
  },
  list_created(filter?: WebhookFilter) {
    return providerTrigger("clickup", "list.created", filter);
  },
  list_deleted(filter?: WebhookFilter) {
    return providerTrigger("clickup", "list.deleted", filter);
  },
  list_updated(filter?: WebhookFilter) {
    return providerTrigger("clickup", "list.updated", filter);
  },
  space_created(filter?: WebhookFilter) {
    return providerTrigger("clickup", "space.created", filter);
  },
  space_deleted(filter?: WebhookFilter) {
    return providerTrigger("clickup", "space.deleted", filter);
  },
  space_updated(filter?: WebhookFilter) {
    return providerTrigger("clickup", "space.updated", filter);
  },
  task_created(filter?: WebhookFilter) {
    return providerTrigger("clickup", "task.created", filter);
  },
  task_deleted(filter?: WebhookFilter) {
    return providerTrigger("clickup", "task.deleted", filter);
  },
  task_updated(filter?: WebhookFilter) {
    return providerTrigger("clickup", "task.updated", filter);
  },
});
