// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const cloudflare = Object.freeze({
  access_custom_certificate_expiration_type(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "access_custom_certificate_expiration_type", filter);
  },
  advanced_http_alert_error(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "advanced_http_alert_error", filter);
  },
  billing_usage_alert(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "billing_usage_alert", filter);
  },
  dedicated_ssl_certificate_event_type(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "dedicated_ssl_certificate_event_type", filter);
  },
  health_check_status_notification(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "health_check_status_notification", filter);
  },
  http_alert_origin_error(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "http_alert_origin_error", filter);
  },
  workers_alert(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "workers_alert", filter);
  },
  workers_observability_alert(filter?: WebhookFilter) {
    return providerTrigger("cloudflare", "workers_observability_alert", filter);
  },
});
