// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const confluence = Object.freeze({
  page_created(filter?: WebhookFilter) {
    return providerTrigger("confluence", "page.created", filter);
  },
  page_deleted(filter?: WebhookFilter) {
    return providerTrigger("confluence", "page.deleted", filter);
  },
  page_updated(filter?: WebhookFilter) {
    return providerTrigger("confluence", "page.updated", filter);
  },
  space_created(filter?: WebhookFilter) {
    return providerTrigger("confluence", "space.created", filter);
  },
  space_deleted(filter?: WebhookFilter) {
    return providerTrigger("confluence", "space.deleted", filter);
  },
  space_updated(filter?: WebhookFilter) {
    return providerTrigger("confluence", "space.updated", filter);
  },
});
