// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const daytona = Object.freeze({
  sandbox_created(filter?: WebhookFilter) {
    return providerTrigger("daytona", "sandbox.created", filter);
  },
  sandbox_state_updated(filter?: WebhookFilter) {
    return providerTrigger("daytona", "sandbox.state.updated", filter);
  },
  snapshot_created(filter?: WebhookFilter) {
    return providerTrigger("daytona", "snapshot.created", filter);
  },
  snapshot_removed(filter?: WebhookFilter) {
    return providerTrigger("daytona", "snapshot.removed", filter);
  },
  snapshot_state_updated(filter?: WebhookFilter) {
    return providerTrigger("daytona", "snapshot.state.updated", filter);
  },
  volume_created(filter?: WebhookFilter) {
    return providerTrigger("daytona", "volume.created", filter);
  },
  volume_state_updated(filter?: WebhookFilter) {
    return providerTrigger("daytona", "volume.state.updated", filter);
  },
});
