// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const docker_hub = Object.freeze({
  push(filter?: WebhookFilter) {
    return providerTrigger("docker-hub", "push", filter);
  },
});
