// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const dropbox = Object.freeze({
  file_changed(filter?: WebhookFilter) {
    return providerTrigger("dropbox", "file.changed", filter);
  },
});
