// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const fathom = Object.freeze({
  new_meeting_content_ready(filter?: WebhookFilter) {
    return providerTrigger("fathom", "new-meeting-content-ready", filter);
  },
});
