// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const gcp = Object.freeze({
  billing_budget_alert(filter?: WebhookFilter) {
    return providerTrigger("gcp", "billing.budget.alert", filter);
  },
  cloud_run_service_created(filter?: WebhookFilter) {
    return providerTrigger("gcp", "cloud-run.service.created", filter);
  },
  cloud_run_service_deleted(filter?: WebhookFilter) {
    return providerTrigger("gcp", "cloud-run.service.deleted", filter);
  },
  cloud_run_service_updated(filter?: WebhookFilter) {
    return providerTrigger("gcp", "cloud-run.service.updated", filter);
  },
  error_reporting_event_logged(filter?: WebhookFilter) {
    return providerTrigger("gcp", "error-reporting.event.logged", filter);
  },
  error_reporting_group_opened(filter?: WebhookFilter) {
    return providerTrigger("gcp", "error-reporting.group.opened", filter);
  },
  error_reporting_group_reopened(filter?: WebhookFilter) {
    return providerTrigger("gcp", "error-reporting.group.reopened", filter);
  },
  monitoring_incident_closed(filter?: WebhookFilter) {
    return providerTrigger("gcp", "monitoring.incident.closed", filter);
  },
  monitoring_incident_open(filter?: WebhookFilter) {
    return providerTrigger("gcp", "monitoring.incident.open", filter);
  },
});
