// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger, triggerArgument } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const github = Object.freeze({
  check_run(action?: string) {
    return providerTrigger("github", "check_run", action === undefined ? undefined : { action: triggerArgument(action, "action") });
  },
  issue_comment(action?: string) {
    return providerTrigger("github", "issue_comment", action === undefined ? undefined : { action: triggerArgument(action, "action") });
  },
  issues(filter?: WebhookFilter) {
    return providerTrigger("github", "issues", filter);
  },
  pull_request(action?: string) {
    return providerTrigger("github", "pull_request", action === undefined ? undefined : { action: triggerArgument(action, "action") });
  },
  pull_request_review(filter?: WebhookFilter) {
    return providerTrigger("github", "pull_request_review", filter);
  },
  push(filter?: WebhookFilter) {
    return providerTrigger("github", "push", filter);
  },
});
