// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const gitlab = Object.freeze({
  build(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build", filter);
  },
  deployment(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment", filter);
  },
  issue(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "issue", filter);
  },
  merge_request(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request", filter);
  },
  note(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "note", filter);
  },
  pipeline(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline", filter);
  },
  push(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "push", filter);
  },
  tag_push(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "tag_push", filter);
  },
});
