// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const gitlab = Object.freeze({
  build(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build", filter);
  },
  deployment(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment", filter);
  },
  issue(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "issue", filter);
  },
  merge_request(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request", filter);
  },
  note(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "note", filter);
  },
  pipeline(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline", filter);
  },
  push(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "push", filter);
  },
  tag_push(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "tag_push", filter);
  },
  build_canceled(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.canceled", filter);
  },
  build_created(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.created", filter);
  },
  build_failed(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.failed", filter);
  },
  build_manual(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.manual", filter);
  },
  build_pending(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.pending", filter);
  },
  build_running(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.running", filter);
  },
  build_skipped(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.skipped", filter);
  },
  build_success(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "build.success", filter);
  },
  deployment_canceled(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment.canceled", filter);
  },
  deployment_created(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment.created", filter);
  },
  deployment_failed(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment.failed", filter);
  },
  deployment_running(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment.running", filter);
  },
  deployment_success(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "deployment.success", filter);
  },
  issue_close(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "issue.close", filter);
  },
  issue_open(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "issue.open", filter);
  },
  issue_reopen(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "issue.reopen", filter);
  },
  issue_update(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "issue.update", filter);
  },
  job_canceled(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.canceled", filter);
  },
  job_created(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.created", filter);
  },
  job_failed(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.failed", filter);
  },
  job_manual(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.manual", filter);
  },
  job_pending(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.pending", filter);
  },
  job_running(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.running", filter);
  },
  job_skipped(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.skipped", filter);
  },
  job_success(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "job.success", filter);
  },
  merge_request_approved(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.approved", filter);
  },
  merge_request_close(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.close", filter);
  },
  merge_request_merge(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.merge", filter);
  },
  merge_request_open(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.open", filter);
  },
  merge_request_reopen(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.reopen", filter);
  },
  merge_request_unapproved(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.unapproved", filter);
  },
  merge_request_update(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "merge_request.update", filter);
  },
  note_Commit(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "note.Commit", filter);
  },
  note_Issue(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "note.Issue", filter);
  },
  note_MergeRequest(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "note.MergeRequest", filter);
  },
  note_Snippet(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "note.Snippet", filter);
  },
  pipeline_canceled(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.canceled", filter);
  },
  pipeline_created(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.created", filter);
  },
  pipeline_failed(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.failed", filter);
  },
  pipeline_manual(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.manual", filter);
  },
  pipeline_pending(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.pending", filter);
  },
  pipeline_running(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.running", filter);
  },
  pipeline_skipped(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.skipped", filter);
  },
  pipeline_success(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.success", filter);
  },
  pipeline_waiting_for_resource(filter?: WebhookFilter) {
    return providerTrigger("gitlab", "pipeline.waiting_for_resource", filter);
  },
});
