// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const google_calendar = Object.freeze({
  calendar_exists(filter?: WebhookFilter) {
    return providerTrigger("google-calendar", "calendar.exists", filter);
  },
  calendar_not_exists(filter?: WebhookFilter) {
    return providerTrigger("google-calendar", "calendar.not_exists", filter);
  },
  calendar_sync(filter?: WebhookFilter) {
    return providerTrigger("google-calendar", "calendar.sync", filter);
  },
});
