// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const granola = Object.freeze({
  file_created(filter?: WebhookFilter) {
    return providerTrigger("granola", "file.created", filter);
  },
  note_access_granted(filter?: WebhookFilter) {
    return providerTrigger("granola", "note.access_granted", filter);
  },
  note_edited(filter?: WebhookFilter) {
    return providerTrigger("granola", "note.edited", filter);
  },
  note_generated(filter?: WebhookFilter) {
    return providerTrigger("granola", "note.generated", filter);
  },
});
