// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const hubspot = Object.freeze({
  company_associationChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "company.associationChange", filter);
  },
  company_created(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "company.created", filter);
  },
  company_deleted(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "company.deleted", filter);
  },
  company_merged(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "company.merged", filter);
  },
  company_propertyChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "company.propertyChange", filter);
  },
  contact_associationChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "contact.associationChange", filter);
  },
  contact_created(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "contact.created", filter);
  },
  contact_deleted(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "contact.deleted", filter);
  },
  contact_merged(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "contact.merged", filter);
  },
  contact_propertyChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "contact.propertyChange", filter);
  },
  deal_associationChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "deal.associationChange", filter);
  },
  deal_created(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "deal.created", filter);
  },
  deal_deleted(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "deal.deleted", filter);
  },
  deal_merged(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "deal.merged", filter);
  },
  deal_propertyChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "deal.propertyChange", filter);
  },
  ticket_associationChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "ticket.associationChange", filter);
  },
  ticket_created(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "ticket.created", filter);
  },
  ticket_deleted(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "ticket.deleted", filter);
  },
  ticket_merged(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "ticket.merged", filter);
  },
  ticket_propertyChange(filter?: WebhookFilter) {
    return providerTrigger("hubspot", "ticket.propertyChange", filter);
  },
});
