// GENERATED by scripts/generate-triggers.mjs — do not edit.

export { airtable } from "./airtable.js";
export { asana } from "./asana.js";
export { azure_blob } from "./azure-blob.js";
export { box } from "./box.js";
export { calendly } from "./calendly.js";
export { clickup } from "./clickup.js";
export { cloudflare } from "./cloudflare.js";
export { confluence } from "./confluence.js";
export { daytona } from "./daytona.js";
export { docker_hub } from "./docker-hub.js";
export { dropbox } from "./dropbox.js";
export { fathom } from "./fathom.js";
export { gcp } from "./gcp.js";
export { gcs } from "./gcs.js";
export { github } from "./github.js";
export { gitlab } from "./gitlab.js";
export { gmail } from "./gmail.js";
export { google_calendar } from "./google-calendar.js";
export { google_drive } from "./google-drive.js";
export { granola } from "./granola.js";
export { hubspot } from "./hubspot.js";
export { intercom } from "./intercom.js";
export { jira } from "./jira.js";
export { linear } from "./linear.js";
export { mailgun } from "./mailgun.js";
export { mixpanel } from "./mixpanel.js";
export { neon } from "./neon.js";
export { notion } from "./notion.js";
export { onedrive } from "./onedrive.js";
export { pipedrive } from "./pipedrive.js";
export { postgres } from "./postgres.js";
export { posthog } from "./posthog.js";
export { ramp } from "./ramp.js";
export { recall } from "./recall.js";
export { redis } from "./redis.js";
export { s3 } from "./s3.js";
export { salesforce } from "./salesforce.js";
export { segment } from "./segment.js";
export { sendgrid } from "./sendgrid.js";
export { sharepoint } from "./sharepoint.js";
export { shopify } from "./shopify.js";
export { shortcut } from "./shortcut.js";
export { slack } from "./slack.js";
export { stripe } from "./stripe.js";
export { teams } from "./teams.js";
export { telegram } from "./telegram.js";
export { zendesk } from "./zendesk.js";

/** Exact upstream event names, plus the generated Slack mention shorthand. */
export const providerEventTypes = Object.freeze({
  "airtable": Object.freeze(["base.create","base.delete","base.update","record.create","record.delete","record.update","table.create","table.delete","table.update"] as const),
  "asana": Object.freeze(["project.added","project.changed","project.deleted","project.removed","section.added","section.changed","section.deleted","section.removed","task.added","task.changed","task.completed","task.deleted","task.removed","workspace.added","workspace.changed","workspace.deleted","workspace.removed"] as const),
  "azure-blob": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "box": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "calendly": Object.freeze(["event_type.canceled","event_type.created","event_type.deleted","event_type.updated","invitee.canceled","invitee.created","invitee.deleted","invitee.updated","scheduled_event.canceled","scheduled_event.created","scheduled_event.deleted","scheduled_event.updated"] as const),
  "clickup": Object.freeze(["folder.created","folder.deleted","folder.updated","list.created","list.deleted","list.updated","space.created","space.deleted","space.updated","task.created","task.deleted","task.updated"] as const),
  "cloudflare": Object.freeze(["access_custom_certificate_expiration_type","advanced_http_alert_error","billing_usage_alert","dedicated_ssl_certificate_event_type","health_check_status_notification","http_alert_origin_error","workers_alert","workers_observability_alert"] as const),
  "confluence": Object.freeze(["page.created","page.deleted","page.updated","space.created","space.deleted","space.updated"] as const),
  "daytona": Object.freeze(["sandbox.created","sandbox.state.updated","snapshot.created","snapshot.removed","snapshot.state.updated","volume.created","volume.state.updated"] as const),
  "docker-hub": Object.freeze(["push"] as const),
  "dropbox": Object.freeze(["file.changed"] as const),
  "fathom": Object.freeze(["new-meeting-content-ready"] as const),
  "gcp": Object.freeze(["billing.budget.alert","cloud-run.service.created","cloud-run.service.deleted","cloud-run.service.updated","error-reporting.event.logged","error-reporting.group.opened","error-reporting.group.reopened","monitoring.incident.closed","monitoring.incident.open"] as const),
  "gcs": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "github": Object.freeze(["check_run","check_run.completed","deployment_status.created","issue_comment","issue_comment.created","issues","issues.closed","issues.edited","issues.labeled","issues.opened","issues.reopened","issues.unlabeled","pull_request","pull_request.closed","pull_request.edited","pull_request.labeled","pull_request.opened","pull_request.ready_for_review","pull_request.reopened","pull_request.synchronize","pull_request.unlabeled","pull_request_review","pull_request_review.dismissed","pull_request_review.edited","pull_request_review.submitted","pull_request_review_comment.created","pull_request_review_thread.resolved","push","status"] as const),
  "gitlab": Object.freeze(["build","build.canceled","build.created","build.failed","build.manual","build.pending","build.running","build.skipped","build.success","deployment","deployment.canceled","deployment.created","deployment.failed","deployment.running","deployment.success","issue","issue.close","issue.open","issue.reopen","issue.update","job.canceled","job.created","job.failed","job.manual","job.pending","job.running","job.skipped","job.success","merge_request","merge_request.approved","merge_request.close","merge_request.merge","merge_request.open","merge_request.reopen","merge_request.unapproved","merge_request.update","note","note.Commit","note.Issue","note.MergeRequest","note.Snippet","pipeline","pipeline.canceled","pipeline.created","pipeline.failed","pipeline.manual","pipeline.pending","pipeline.running","pipeline.skipped","pipeline.success","pipeline.waiting_for_resource","push","tag_push"] as const),
  "gmail": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "google-calendar": Object.freeze(["calendar.exists","calendar.not_exists","calendar.sync"] as const),
  "google-drive": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "granola": Object.freeze(["file.created","note.access_granted","note.edited","note.generated"] as const),
  "hubspot": Object.freeze(["company.associationChange","company.created","company.deleted","company.merged","company.propertyChange","contact.associationChange","contact.created","contact.deleted","contact.merged","contact.propertyChange","deal.associationChange","deal.created","deal.deleted","deal.merged","deal.propertyChange","ticket.associationChange","ticket.created","ticket.deleted","ticket.merged","ticket.propertyChange"] as const),
  "intercom": Object.freeze(["company.archived","company.closed","company.created","company.deleted","company.reopened","company.updated","contact.archived","contact.closed","contact.created","contact.deleted","contact.reopened","contact.updated","conversation.archived","conversation.closed","conversation.created","conversation.deleted","conversation.reopened","conversation.updated"] as const),
  "jira": Object.freeze(["comment.created","comment.deleted","comment.updated","issue.created","issue.deleted","issue.updated","project.created","project.deleted","project.updated","sprint.created","sprint.deleted","sprint.updated"] as const),
  "linear": Object.freeze(["AgentSessionEvent.created","AgentSessionEvent.prompted","AppUserNotification.issueAssignedToYou","AppUserNotification.issueCommentMention","AppUserNotification.issueCommentReaction","AppUserNotification.issueEmojiReaction","AppUserNotification.issueMention","AppUserNotification.issueNewComment","AppUserNotification.issueStatusChanged","AppUserNotification.issueUnassignedFromYou","OAuthApp.revoked","PermissionChange.teamAccessChanged","comment.create","comment.remove","comment.update","cycle.create","cycle.remove","cycle.update","issue.create","issue.remove","issue.update","label.create","label.remove","label.update","milestone.create","milestone.remove","milestone.update","project.create","project.remove","project.update","roadmap.create","roadmap.remove","roadmap.update"] as const),
  "mailgun": Object.freeze(["event.accepted","event.clicked","event.complained","event.delivered","event.failed","event.opened","event.permanent_fail","event.stored","event.unsubscribed","list.created","list.updated","message.accepted","message.delivered","message.failed","message.stored"] as const),
  "mixpanel": Object.freeze(["cohort.create","cohort.delete","cohort.merge","cohort.update","event.create","event.delete","event.merge","event.update","profile.create","profile.delete","profile.merge","profile.update"] as const),
  "neon": Object.freeze(["advisor.issue_raised","endpoint.state_changed","operation.cancelled","operation.failed","operation.succeeded"] as const),
  "notion": Object.freeze(["database.created","database.deleted","database.moved","database.schema_updated","database.undeleted","page.content_updated","page.created","page.deleted","page.locked","page.moved","page.properties_updated","page.undeleted","page.unlocked"] as const),
  "onedrive": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "pipedrive": Object.freeze(["activity.created","activity.deleted","activity.updated","deal.created","deal.deleted","deal.lost","deal.updated","deal.won","organization.created","organization.deleted","organization.updated","person.created","person.deleted","person.updated"] as const),
  "postgres": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "posthog": Object.freeze(["posthog.alert.resolved","posthog.alert.triggered"] as const),
  "ramp": Object.freeze(["applications.status_updated","bills.approved","bills.archived","bills.created","bills.paid","bills.ready_to_sync","bills.rejected","bills.updated","entities.created","item_receipts.created","payments.updated","purchase_orders.archived","purchase_orders.created","purchase_orders.updated","reimbursements.batch_payment_reimbursed","reimbursements.ready_for_review","reimbursements.ready_to_sync","reimbursements.sync_requested","spend_requests.comment_created","spend_requests.created","transactions.all_requirements_met_and_approved_changed","transactions.authorized","transactions.body_coding_updated","transactions.cleared","transactions.declined","transactions.ready_for_review","transactions.ready_to_sync","transactions.receipt_added","transactions.sync_requested","transactions.synced","unified_requests.created","unified_requests.external_approval_request","unified_requests.external_approval_request_reset","unified_requests.modified","unified_requests.node_advanced","unified_requests.override_approved","unified_requests.updated","users.invite_accepted","vendor_agreements.archived","vendor_agreements.created","vendor_agreements.deleted","vendor_agreements.document_added","vendor_agreements.renewal_milestone","vendor_agreements.updated","vendors.activated","vendors.approved","vendors.updated"] as const),
  "recall": Object.freeze(["file.created","recording.created","transcript.done"] as const),
  "redis": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "s3": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "salesforce": Object.freeze(["Account.created","Account.deleted","Account.updated","Account.upserted","Case.closed","Case.created","Case.deleted","Case.updated","Case.upserted","Contact.created","Contact.deleted","Contact.updated","Contact.upserted","Lead.converted","Lead.created","Lead.deleted","Lead.updated","Lead.upserted","Opportunity.created","Opportunity.deleted","Opportunity.updated","Opportunity.upserted"] as const),
  "segment": Object.freeze(["group.create","group.update","group.upsert","identify.create","identify.update","identify.upsert","page.create","page.update","page.upsert","track.create","track.update","track.upsert"] as const),
  "sendgrid": Object.freeze(["contact.create","contact.delete","contact.update","event.bounce","event.click","event.deferred","event.delivered","event.dropped","event.group_resubscribe","event.group_unsubscribe","event.open","event.processed","event.spamreport","event.unsubscribe","mail.create","mail.delete","mail.update"] as const),
  "sharepoint": Object.freeze(["file.created","file.deleted","file.updated"] as const),
  "shopify": Object.freeze(["customer.cancel","customer.create","customer.delete","customer.fulfill","customer.paid","customer.update","fulfillment.cancel","fulfillment.create","fulfillment.delete","fulfillment.fulfill","fulfillment.paid","fulfillment.update","order.cancel","order.create","order.delete","order.fulfill","order.paid","order.update","product.cancel","product.create","product.delete","product.fulfill","product.paid","product.update"] as const),
  "shortcut": Object.freeze(["epic.create","epic.delete","epic.update","story.create","story.delete","story.update"] as const),
  "slack": Object.freeze(["app_mention","channel.archived","channel.created","channel.deleted","channel.member_joined","channel.member_left","channel.renamed","channel.unarchived","group.archived","group.deleted","group.renamed","group.unarchived","message","message.created","message.deleted","message.updated","reaction.added","reaction.removed","reaction_added","user.changed","user.joined"] as const),
  "stripe": Object.freeze(["charge.failed","charge.refunded","charge.succeeded","charge.updated","customer.created","customer.deleted","customer.subscription.created","customer.subscription.deleted","customer.subscription.updated","customer.updated","invoice.created","invoice.finalized","invoice.paid","invoice.payment_failed","invoice.updated","invoice.voided","payment_intent.canceled","payment_intent.created","payment_intent.payment_failed","payment_intent.requires_action","payment_intent.succeeded"] as const),
  "teams": Object.freeze(["channel.created","channel.deleted","channel.updated","chat.created","chat.deleted","chat.updated","chat_message.created","chat_message.deleted","chat_message.updated","member.created","member.deleted","member.updated","message.created","message.deleted","message.updated","reply.created","reply.deleted","reply.updated","team.deleted","team.updated"] as const),
  "telegram": Object.freeze(["business_connection","business_message","callback_query","channel_post","chat_boost","chat_join_request","chat_member","chosen_inline_result","deleted_business_messages","edited_business_message","edited_channel_post","edited_message","guest_message","inline_query","managed_bot","message","message_reaction","message_reaction_count","my_chat_member","poll","poll_answer","pre_checkout_query","purchased_paid_media","removed_chat_boost","shipping_query"] as const),
  "zendesk": Object.freeze(["organization.created","organization.deleted","organization.updated","ticket.created","ticket.deleted","ticket.updated","user.created","user.deleted","user.updated"] as const),
});
