// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const intercom = Object.freeze({
  company_archived(filter?: WebhookFilter) {
    return providerTrigger("intercom", "company.archived", filter);
  },
  company_closed(filter?: WebhookFilter) {
    return providerTrigger("intercom", "company.closed", filter);
  },
  company_created(filter?: WebhookFilter) {
    return providerTrigger("intercom", "company.created", filter);
  },
  company_deleted(filter?: WebhookFilter) {
    return providerTrigger("intercom", "company.deleted", filter);
  },
  company_reopened(filter?: WebhookFilter) {
    return providerTrigger("intercom", "company.reopened", filter);
  },
  company_updated(filter?: WebhookFilter) {
    return providerTrigger("intercom", "company.updated", filter);
  },
  contact_archived(filter?: WebhookFilter) {
    return providerTrigger("intercom", "contact.archived", filter);
  },
  contact_closed(filter?: WebhookFilter) {
    return providerTrigger("intercom", "contact.closed", filter);
  },
  contact_created(filter?: WebhookFilter) {
    return providerTrigger("intercom", "contact.created", filter);
  },
  contact_deleted(filter?: WebhookFilter) {
    return providerTrigger("intercom", "contact.deleted", filter);
  },
  contact_reopened(filter?: WebhookFilter) {
    return providerTrigger("intercom", "contact.reopened", filter);
  },
  contact_updated(filter?: WebhookFilter) {
    return providerTrigger("intercom", "contact.updated", filter);
  },
  conversation_archived(filter?: WebhookFilter) {
    return providerTrigger("intercom", "conversation.archived", filter);
  },
  conversation_closed(filter?: WebhookFilter) {
    return providerTrigger("intercom", "conversation.closed", filter);
  },
  conversation_created(filter?: WebhookFilter) {
    return providerTrigger("intercom", "conversation.created", filter);
  },
  conversation_deleted(filter?: WebhookFilter) {
    return providerTrigger("intercom", "conversation.deleted", filter);
  },
  conversation_reopened(filter?: WebhookFilter) {
    return providerTrigger("intercom", "conversation.reopened", filter);
  },
  conversation_updated(filter?: WebhookFilter) {
    return providerTrigger("intercom", "conversation.updated", filter);
  },
});
