// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const jira = Object.freeze({
  comment_created(filter?: WebhookFilter) {
    return providerTrigger("jira", "comment.created", filter);
  },
  comment_deleted(filter?: WebhookFilter) {
    return providerTrigger("jira", "comment.deleted", filter);
  },
  comment_updated(filter?: WebhookFilter) {
    return providerTrigger("jira", "comment.updated", filter);
  },
  issue_created(filter?: WebhookFilter) {
    return providerTrigger("jira", "issue.created", filter);
  },
  issue_deleted(filter?: WebhookFilter) {
    return providerTrigger("jira", "issue.deleted", filter);
  },
  issue_updated(filter?: WebhookFilter) {
    return providerTrigger("jira", "issue.updated", filter);
  },
  project_created(filter?: WebhookFilter) {
    return providerTrigger("jira", "project.created", filter);
  },
  project_deleted(filter?: WebhookFilter) {
    return providerTrigger("jira", "project.deleted", filter);
  },
  project_updated(filter?: WebhookFilter) {
    return providerTrigger("jira", "project.updated", filter);
  },
  sprint_created(filter?: WebhookFilter) {
    return providerTrigger("jira", "sprint.created", filter);
  },
  sprint_deleted(filter?: WebhookFilter) {
    return providerTrigger("jira", "sprint.deleted", filter);
  },
  sprint_updated(filter?: WebhookFilter) {
    return providerTrigger("jira", "sprint.updated", filter);
  },
});
