// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const linear = Object.freeze({
  AgentSessionEvent_created(filter?: WebhookFilter) {
    return providerTrigger("linear", "AgentSessionEvent.created", filter);
  },
  AgentSessionEvent_prompted(filter?: WebhookFilter) {
    return providerTrigger("linear", "AgentSessionEvent.prompted", filter);
  },
  AppUserNotification_issueAssignedToYou(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueAssignedToYou", filter);
  },
  AppUserNotification_issueCommentMention(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueCommentMention", filter);
  },
  AppUserNotification_issueCommentReaction(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueCommentReaction", filter);
  },
  AppUserNotification_issueEmojiReaction(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueEmojiReaction", filter);
  },
  AppUserNotification_issueMention(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueMention", filter);
  },
  AppUserNotification_issueNewComment(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueNewComment", filter);
  },
  AppUserNotification_issueStatusChanged(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueStatusChanged", filter);
  },
  AppUserNotification_issueUnassignedFromYou(filter?: WebhookFilter) {
    return providerTrigger("linear", "AppUserNotification.issueUnassignedFromYou", filter);
  },
  comment_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "comment.create", filter);
  },
  comment_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "comment.remove", filter);
  },
  comment_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "comment.update", filter);
  },
  cycle_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "cycle.create", filter);
  },
  cycle_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "cycle.remove", filter);
  },
  cycle_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "cycle.update", filter);
  },
  issue_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "issue.create", filter);
  },
  issue_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "issue.remove", filter);
  },
  issue_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "issue.update", filter);
  },
  label_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "label.create", filter);
  },
  label_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "label.remove", filter);
  },
  label_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "label.update", filter);
  },
  milestone_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "milestone.create", filter);
  },
  milestone_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "milestone.remove", filter);
  },
  milestone_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "milestone.update", filter);
  },
  OAuthApp_revoked(filter?: WebhookFilter) {
    return providerTrigger("linear", "OAuthApp.revoked", filter);
  },
  PermissionChange_teamAccessChanged(filter?: WebhookFilter) {
    return providerTrigger("linear", "PermissionChange.teamAccessChanged", filter);
  },
  project_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "project.create", filter);
  },
  project_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "project.remove", filter);
  },
  project_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "project.update", filter);
  },
  roadmap_create(filter?: WebhookFilter) {
    return providerTrigger("linear", "roadmap.create", filter);
  },
  roadmap_remove(filter?: WebhookFilter) {
    return providerTrigger("linear", "roadmap.remove", filter);
  },
  roadmap_update(filter?: WebhookFilter) {
    return providerTrigger("linear", "roadmap.update", filter);
  },
});
