// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const mailgun = Object.freeze({
  event_accepted(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.accepted", filter);
  },
  event_clicked(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.clicked", filter);
  },
  event_complained(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.complained", filter);
  },
  event_delivered(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.delivered", filter);
  },
  event_failed(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.failed", filter);
  },
  event_opened(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.opened", filter);
  },
  event_permanent_fail(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.permanent_fail", filter);
  },
  event_stored(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.stored", filter);
  },
  event_unsubscribed(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "event.unsubscribed", filter);
  },
  list_created(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "list.created", filter);
  },
  list_updated(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "list.updated", filter);
  },
  message_accepted(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "message.accepted", filter);
  },
  message_delivered(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "message.delivered", filter);
  },
  message_failed(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "message.failed", filter);
  },
  message_stored(filter?: WebhookFilter) {
    return providerTrigger("mailgun", "message.stored", filter);
  },
});
