// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const mixpanel = Object.freeze({
  cohort_create(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "cohort.create", filter);
  },
  cohort_delete(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "cohort.delete", filter);
  },
  cohort_merge(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "cohort.merge", filter);
  },
  cohort_update(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "cohort.update", filter);
  },
  event_create(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "event.create", filter);
  },
  event_delete(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "event.delete", filter);
  },
  event_merge(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "event.merge", filter);
  },
  event_update(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "event.update", filter);
  },
  profile_create(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "profile.create", filter);
  },
  profile_delete(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "profile.delete", filter);
  },
  profile_merge(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "profile.merge", filter);
  },
  profile_update(filter?: WebhookFilter) {
    return providerTrigger("mixpanel", "profile.update", filter);
  },
});
