// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const neon = Object.freeze({
  advisor_issue_raised(filter?: WebhookFilter) {
    return providerTrigger("neon", "advisor.issue_raised", filter);
  },
  endpoint_state_changed(filter?: WebhookFilter) {
    return providerTrigger("neon", "endpoint.state_changed", filter);
  },
  operation_cancelled(filter?: WebhookFilter) {
    return providerTrigger("neon", "operation.cancelled", filter);
  },
  operation_failed(filter?: WebhookFilter) {
    return providerTrigger("neon", "operation.failed", filter);
  },
  operation_succeeded(filter?: WebhookFilter) {
    return providerTrigger("neon", "operation.succeeded", filter);
  },
});
