// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const notion = Object.freeze({
  database_created(filter?: WebhookFilter) {
    return providerTrigger("notion", "database.created", filter);
  },
  database_deleted(filter?: WebhookFilter) {
    return providerTrigger("notion", "database.deleted", filter);
  },
  database_moved(filter?: WebhookFilter) {
    return providerTrigger("notion", "database.moved", filter);
  },
  database_schema_updated(filter?: WebhookFilter) {
    return providerTrigger("notion", "database.schema_updated", filter);
  },
  database_undeleted(filter?: WebhookFilter) {
    return providerTrigger("notion", "database.undeleted", filter);
  },
  page_content_updated(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.content_updated", filter);
  },
  page_created(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.created", filter);
  },
  page_deleted(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.deleted", filter);
  },
  page_locked(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.locked", filter);
  },
  page_moved(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.moved", filter);
  },
  page_properties_updated(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.properties_updated", filter);
  },
  page_undeleted(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.undeleted", filter);
  },
  page_unlocked(filter?: WebhookFilter) {
    return providerTrigger("notion", "page.unlocked", filter);
  },
});
