// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const pipedrive = Object.freeze({
  activity_created(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "activity.created", filter);
  },
  activity_deleted(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "activity.deleted", filter);
  },
  activity_updated(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "activity.updated", filter);
  },
  deal_created(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "deal.created", filter);
  },
  deal_deleted(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "deal.deleted", filter);
  },
  deal_lost(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "deal.lost", filter);
  },
  deal_updated(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "deal.updated", filter);
  },
  deal_won(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "deal.won", filter);
  },
  organization_created(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "organization.created", filter);
  },
  organization_deleted(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "organization.deleted", filter);
  },
  organization_updated(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "organization.updated", filter);
  },
  person_created(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "person.created", filter);
  },
  person_deleted(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "person.deleted", filter);
  },
  person_updated(filter?: WebhookFilter) {
    return providerTrigger("pipedrive", "person.updated", filter);
  },
});
