// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const posthog = Object.freeze({
  posthog_alert_resolved(filter?: WebhookFilter) {
    return providerTrigger("posthog", "posthog.alert.resolved", filter);
  },
  posthog_alert_triggered(filter?: WebhookFilter) {
    return providerTrigger("posthog", "posthog.alert.triggered", filter);
  },
});
