// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const ramp = Object.freeze({
  applications_status_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "applications.status_updated", filter);
  },
  bills_approved(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.approved", filter);
  },
  bills_archived(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.archived", filter);
  },
  bills_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.created", filter);
  },
  bills_paid(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.paid", filter);
  },
  bills_ready_to_sync(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.ready_to_sync", filter);
  },
  bills_rejected(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.rejected", filter);
  },
  bills_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "bills.updated", filter);
  },
  entities_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "entities.created", filter);
  },
  item_receipts_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "item_receipts.created", filter);
  },
  payments_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "payments.updated", filter);
  },
  purchase_orders_archived(filter?: WebhookFilter) {
    return providerTrigger("ramp", "purchase_orders.archived", filter);
  },
  purchase_orders_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "purchase_orders.created", filter);
  },
  purchase_orders_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "purchase_orders.updated", filter);
  },
  reimbursements_batch_payment_reimbursed(filter?: WebhookFilter) {
    return providerTrigger("ramp", "reimbursements.batch_payment_reimbursed", filter);
  },
  reimbursements_ready_for_review(filter?: WebhookFilter) {
    return providerTrigger("ramp", "reimbursements.ready_for_review", filter);
  },
  reimbursements_ready_to_sync(filter?: WebhookFilter) {
    return providerTrigger("ramp", "reimbursements.ready_to_sync", filter);
  },
  reimbursements_sync_requested(filter?: WebhookFilter) {
    return providerTrigger("ramp", "reimbursements.sync_requested", filter);
  },
  spend_requests_comment_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "spend_requests.comment_created", filter);
  },
  spend_requests_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "spend_requests.created", filter);
  },
  transactions_all_requirements_met_and_approved_changed(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.all_requirements_met_and_approved_changed", filter);
  },
  transactions_authorized(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.authorized", filter);
  },
  transactions_body_coding_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.body_coding_updated", filter);
  },
  transactions_cleared(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.cleared", filter);
  },
  transactions_declined(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.declined", filter);
  },
  transactions_ready_for_review(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.ready_for_review", filter);
  },
  transactions_ready_to_sync(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.ready_to_sync", filter);
  },
  transactions_receipt_added(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.receipt_added", filter);
  },
  transactions_sync_requested(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.sync_requested", filter);
  },
  transactions_synced(filter?: WebhookFilter) {
    return providerTrigger("ramp", "transactions.synced", filter);
  },
  unified_requests_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.created", filter);
  },
  unified_requests_external_approval_request(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.external_approval_request", filter);
  },
  unified_requests_external_approval_request_reset(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.external_approval_request_reset", filter);
  },
  unified_requests_modified(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.modified", filter);
  },
  unified_requests_node_advanced(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.node_advanced", filter);
  },
  unified_requests_override_approved(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.override_approved", filter);
  },
  unified_requests_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "unified_requests.updated", filter);
  },
  users_invite_accepted(filter?: WebhookFilter) {
    return providerTrigger("ramp", "users.invite_accepted", filter);
  },
  vendor_agreements_archived(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendor_agreements.archived", filter);
  },
  vendor_agreements_created(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendor_agreements.created", filter);
  },
  vendor_agreements_deleted(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendor_agreements.deleted", filter);
  },
  vendor_agreements_document_added(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendor_agreements.document_added", filter);
  },
  vendor_agreements_renewal_milestone(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendor_agreements.renewal_milestone", filter);
  },
  vendor_agreements_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendor_agreements.updated", filter);
  },
  vendors_activated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendors.activated", filter);
  },
  vendors_approved(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendors.approved", filter);
  },
  vendors_updated(filter?: WebhookFilter) {
    return providerTrigger("ramp", "vendors.updated", filter);
  },
});
