// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const recall = Object.freeze({
  file_created(filter?: WebhookFilter) {
    return providerTrigger("recall", "file.created", filter);
  },
  recording_created(filter?: WebhookFilter) {
    return providerTrigger("recall", "recording.created", filter);
  },
  transcript_done(filter?: WebhookFilter) {
    return providerTrigger("recall", "transcript.done", filter);
  },
});
