// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const salesforce = Object.freeze({
  Account_created(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Account.created", filter);
  },
  Account_deleted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Account.deleted", filter);
  },
  Account_updated(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Account.updated", filter);
  },
  Account_upserted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Account.upserted", filter);
  },
  Case_closed(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Case.closed", filter);
  },
  Case_created(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Case.created", filter);
  },
  Case_deleted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Case.deleted", filter);
  },
  Case_updated(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Case.updated", filter);
  },
  Case_upserted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Case.upserted", filter);
  },
  Contact_created(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Contact.created", filter);
  },
  Contact_deleted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Contact.deleted", filter);
  },
  Contact_updated(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Contact.updated", filter);
  },
  Contact_upserted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Contact.upserted", filter);
  },
  Lead_converted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Lead.converted", filter);
  },
  Lead_created(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Lead.created", filter);
  },
  Lead_deleted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Lead.deleted", filter);
  },
  Lead_updated(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Lead.updated", filter);
  },
  Lead_upserted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Lead.upserted", filter);
  },
  Opportunity_created(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Opportunity.created", filter);
  },
  Opportunity_deleted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Opportunity.deleted", filter);
  },
  Opportunity_updated(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Opportunity.updated", filter);
  },
  Opportunity_upserted(filter?: WebhookFilter) {
    return providerTrigger("salesforce", "Opportunity.upserted", filter);
  },
});
