// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const segment = Object.freeze({
  group_create(filter?: WebhookFilter) {
    return providerTrigger("segment", "group.create", filter);
  },
  group_update(filter?: WebhookFilter) {
    return providerTrigger("segment", "group.update", filter);
  },
  group_upsert(filter?: WebhookFilter) {
    return providerTrigger("segment", "group.upsert", filter);
  },
  identify_create(filter?: WebhookFilter) {
    return providerTrigger("segment", "identify.create", filter);
  },
  identify_update(filter?: WebhookFilter) {
    return providerTrigger("segment", "identify.update", filter);
  },
  identify_upsert(filter?: WebhookFilter) {
    return providerTrigger("segment", "identify.upsert", filter);
  },
  page_create(filter?: WebhookFilter) {
    return providerTrigger("segment", "page.create", filter);
  },
  page_update(filter?: WebhookFilter) {
    return providerTrigger("segment", "page.update", filter);
  },
  page_upsert(filter?: WebhookFilter) {
    return providerTrigger("segment", "page.upsert", filter);
  },
  track_create(filter?: WebhookFilter) {
    return providerTrigger("segment", "track.create", filter);
  },
  track_update(filter?: WebhookFilter) {
    return providerTrigger("segment", "track.update", filter);
  },
  track_upsert(filter?: WebhookFilter) {
    return providerTrigger("segment", "track.upsert", filter);
  },
});
