// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const sendgrid = Object.freeze({
  contact_create(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "contact.create", filter);
  },
  contact_delete(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "contact.delete", filter);
  },
  contact_update(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "contact.update", filter);
  },
  event_bounce(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.bounce", filter);
  },
  event_click(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.click", filter);
  },
  event_deferred(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.deferred", filter);
  },
  event_delivered(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.delivered", filter);
  },
  event_dropped(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.dropped", filter);
  },
  event_group_resubscribe(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.group_resubscribe", filter);
  },
  event_group_unsubscribe(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.group_unsubscribe", filter);
  },
  event_open(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.open", filter);
  },
  event_processed(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.processed", filter);
  },
  event_spamreport(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.spamreport", filter);
  },
  event_unsubscribe(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "event.unsubscribe", filter);
  },
  mail_create(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "mail.create", filter);
  },
  mail_delete(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "mail.delete", filter);
  },
  mail_update(filter?: WebhookFilter) {
    return providerTrigger("sendgrid", "mail.update", filter);
  },
});
