// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const shopify = Object.freeze({
  customer_cancel(filter?: WebhookFilter) {
    return providerTrigger("shopify", "customer.cancel", filter);
  },
  customer_create(filter?: WebhookFilter) {
    return providerTrigger("shopify", "customer.create", filter);
  },
  customer_delete(filter?: WebhookFilter) {
    return providerTrigger("shopify", "customer.delete", filter);
  },
  customer_fulfill(filter?: WebhookFilter) {
    return providerTrigger("shopify", "customer.fulfill", filter);
  },
  customer_paid(filter?: WebhookFilter) {
    return providerTrigger("shopify", "customer.paid", filter);
  },
  customer_update(filter?: WebhookFilter) {
    return providerTrigger("shopify", "customer.update", filter);
  },
  fulfillment_cancel(filter?: WebhookFilter) {
    return providerTrigger("shopify", "fulfillment.cancel", filter);
  },
  fulfillment_create(filter?: WebhookFilter) {
    return providerTrigger("shopify", "fulfillment.create", filter);
  },
  fulfillment_delete(filter?: WebhookFilter) {
    return providerTrigger("shopify", "fulfillment.delete", filter);
  },
  fulfillment_fulfill(filter?: WebhookFilter) {
    return providerTrigger("shopify", "fulfillment.fulfill", filter);
  },
  fulfillment_paid(filter?: WebhookFilter) {
    return providerTrigger("shopify", "fulfillment.paid", filter);
  },
  fulfillment_update(filter?: WebhookFilter) {
    return providerTrigger("shopify", "fulfillment.update", filter);
  },
  order_cancel(filter?: WebhookFilter) {
    return providerTrigger("shopify", "order.cancel", filter);
  },
  order_create(filter?: WebhookFilter) {
    return providerTrigger("shopify", "order.create", filter);
  },
  order_delete(filter?: WebhookFilter) {
    return providerTrigger("shopify", "order.delete", filter);
  },
  order_fulfill(filter?: WebhookFilter) {
    return providerTrigger("shopify", "order.fulfill", filter);
  },
  order_paid(filter?: WebhookFilter) {
    return providerTrigger("shopify", "order.paid", filter);
  },
  order_update(filter?: WebhookFilter) {
    return providerTrigger("shopify", "order.update", filter);
  },
  product_cancel(filter?: WebhookFilter) {
    return providerTrigger("shopify", "product.cancel", filter);
  },
  product_create(filter?: WebhookFilter) {
    return providerTrigger("shopify", "product.create", filter);
  },
  product_delete(filter?: WebhookFilter) {
    return providerTrigger("shopify", "product.delete", filter);
  },
  product_fulfill(filter?: WebhookFilter) {
    return providerTrigger("shopify", "product.fulfill", filter);
  },
  product_paid(filter?: WebhookFilter) {
    return providerTrigger("shopify", "product.paid", filter);
  },
  product_update(filter?: WebhookFilter) {
    return providerTrigger("shopify", "product.update", filter);
  },
});
