// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const shortcut = Object.freeze({
  epic_create(filter?: WebhookFilter) {
    return providerTrigger("shortcut", "epic.create", filter);
  },
  epic_delete(filter?: WebhookFilter) {
    return providerTrigger("shortcut", "epic.delete", filter);
  },
  epic_update(filter?: WebhookFilter) {
    return providerTrigger("shortcut", "epic.update", filter);
  },
  story_create(filter?: WebhookFilter) {
    return providerTrigger("shortcut", "story.create", filter);
  },
  story_delete(filter?: WebhookFilter) {
    return providerTrigger("shortcut", "story.delete", filter);
  },
  story_update(filter?: WebhookFilter) {
    return providerTrigger("shortcut", "story.update", filter);
  },
});
