// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger, triggerArgument } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const slack = Object.freeze({
  message(filter?: WebhookFilter) {
    return providerTrigger("slack", "message", filter);
  },
  reaction_added(filter?: WebhookFilter) {
    return providerTrigger("slack", "reaction_added", filter);
  },
  mention(channel: string) {
    return providerTrigger("slack", "app_mention", { channel: triggerArgument(channel, "channel") });
  },
  reaction(emoji: string) {
    return providerTrigger("slack", "reaction_added", { reaction: triggerArgument(emoji, "emoji") });
  },
});
