// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const stripe = Object.freeze({
  charge_failed(filter?: WebhookFilter) {
    return providerTrigger("stripe", "charge.failed", filter);
  },
  charge_refunded(filter?: WebhookFilter) {
    return providerTrigger("stripe", "charge.refunded", filter);
  },
  charge_succeeded(filter?: WebhookFilter) {
    return providerTrigger("stripe", "charge.succeeded", filter);
  },
  charge_updated(filter?: WebhookFilter) {
    return providerTrigger("stripe", "charge.updated", filter);
  },
  customer_created(filter?: WebhookFilter) {
    return providerTrigger("stripe", "customer.created", filter);
  },
  customer_deleted(filter?: WebhookFilter) {
    return providerTrigger("stripe", "customer.deleted", filter);
  },
  customer_subscription_created(filter?: WebhookFilter) {
    return providerTrigger("stripe", "customer.subscription.created", filter);
  },
  customer_subscription_deleted(filter?: WebhookFilter) {
    return providerTrigger("stripe", "customer.subscription.deleted", filter);
  },
  customer_subscription_updated(filter?: WebhookFilter) {
    return providerTrigger("stripe", "customer.subscription.updated", filter);
  },
  customer_updated(filter?: WebhookFilter) {
    return providerTrigger("stripe", "customer.updated", filter);
  },
  invoice_created(filter?: WebhookFilter) {
    return providerTrigger("stripe", "invoice.created", filter);
  },
  invoice_finalized(filter?: WebhookFilter) {
    return providerTrigger("stripe", "invoice.finalized", filter);
  },
  invoice_paid(filter?: WebhookFilter) {
    return providerTrigger("stripe", "invoice.paid", filter);
  },
  invoice_payment_failed(filter?: WebhookFilter) {
    return providerTrigger("stripe", "invoice.payment_failed", filter);
  },
  invoice_updated(filter?: WebhookFilter) {
    return providerTrigger("stripe", "invoice.updated", filter);
  },
  invoice_voided(filter?: WebhookFilter) {
    return providerTrigger("stripe", "invoice.voided", filter);
  },
  payment_intent_canceled(filter?: WebhookFilter) {
    return providerTrigger("stripe", "payment_intent.canceled", filter);
  },
  payment_intent_created(filter?: WebhookFilter) {
    return providerTrigger("stripe", "payment_intent.created", filter);
  },
  payment_intent_payment_failed(filter?: WebhookFilter) {
    return providerTrigger("stripe", "payment_intent.payment_failed", filter);
  },
  payment_intent_requires_action(filter?: WebhookFilter) {
    return providerTrigger("stripe", "payment_intent.requires_action", filter);
  },
  payment_intent_succeeded(filter?: WebhookFilter) {
    return providerTrigger("stripe", "payment_intent.succeeded", filter);
  },
});
