// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const teams = Object.freeze({
  channel_created(filter?: WebhookFilter) {
    return providerTrigger("teams", "channel.created", filter);
  },
  channel_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "channel.deleted", filter);
  },
  channel_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "channel.updated", filter);
  },
  chat_created(filter?: WebhookFilter) {
    return providerTrigger("teams", "chat.created", filter);
  },
  chat_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "chat.deleted", filter);
  },
  chat_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "chat.updated", filter);
  },
  chat_message_created(filter?: WebhookFilter) {
    return providerTrigger("teams", "chat_message.created", filter);
  },
  chat_message_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "chat_message.deleted", filter);
  },
  chat_message_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "chat_message.updated", filter);
  },
  member_created(filter?: WebhookFilter) {
    return providerTrigger("teams", "member.created", filter);
  },
  member_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "member.deleted", filter);
  },
  member_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "member.updated", filter);
  },
  message_created(filter?: WebhookFilter) {
    return providerTrigger("teams", "message.created", filter);
  },
  message_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "message.deleted", filter);
  },
  message_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "message.updated", filter);
  },
  reply_created(filter?: WebhookFilter) {
    return providerTrigger("teams", "reply.created", filter);
  },
  reply_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "reply.deleted", filter);
  },
  reply_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "reply.updated", filter);
  },
  team_deleted(filter?: WebhookFilter) {
    return providerTrigger("teams", "team.deleted", filter);
  },
  team_updated(filter?: WebhookFilter) {
    return providerTrigger("teams", "team.updated", filter);
  },
});
