// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const telegram = Object.freeze({
  business_connection(filter?: WebhookFilter) {
    return providerTrigger("telegram", "business_connection", filter);
  },
  business_message(filter?: WebhookFilter) {
    return providerTrigger("telegram", "business_message", filter);
  },
  callback_query(filter?: WebhookFilter) {
    return providerTrigger("telegram", "callback_query", filter);
  },
  channel_post(filter?: WebhookFilter) {
    return providerTrigger("telegram", "channel_post", filter);
  },
  chat_boost(filter?: WebhookFilter) {
    return providerTrigger("telegram", "chat_boost", filter);
  },
  chat_join_request(filter?: WebhookFilter) {
    return providerTrigger("telegram", "chat_join_request", filter);
  },
  chat_member(filter?: WebhookFilter) {
    return providerTrigger("telegram", "chat_member", filter);
  },
  chosen_inline_result(filter?: WebhookFilter) {
    return providerTrigger("telegram", "chosen_inline_result", filter);
  },
  deleted_business_messages(filter?: WebhookFilter) {
    return providerTrigger("telegram", "deleted_business_messages", filter);
  },
  edited_business_message(filter?: WebhookFilter) {
    return providerTrigger("telegram", "edited_business_message", filter);
  },
  edited_channel_post(filter?: WebhookFilter) {
    return providerTrigger("telegram", "edited_channel_post", filter);
  },
  edited_message(filter?: WebhookFilter) {
    return providerTrigger("telegram", "edited_message", filter);
  },
  guest_message(filter?: WebhookFilter) {
    return providerTrigger("telegram", "guest_message", filter);
  },
  inline_query(filter?: WebhookFilter) {
    return providerTrigger("telegram", "inline_query", filter);
  },
  managed_bot(filter?: WebhookFilter) {
    return providerTrigger("telegram", "managed_bot", filter);
  },
  message(filter?: WebhookFilter) {
    return providerTrigger("telegram", "message", filter);
  },
  message_reaction(filter?: WebhookFilter) {
    return providerTrigger("telegram", "message_reaction", filter);
  },
  message_reaction_count(filter?: WebhookFilter) {
    return providerTrigger("telegram", "message_reaction_count", filter);
  },
  my_chat_member(filter?: WebhookFilter) {
    return providerTrigger("telegram", "my_chat_member", filter);
  },
  poll(filter?: WebhookFilter) {
    return providerTrigger("telegram", "poll", filter);
  },
  poll_answer(filter?: WebhookFilter) {
    return providerTrigger("telegram", "poll_answer", filter);
  },
  pre_checkout_query(filter?: WebhookFilter) {
    return providerTrigger("telegram", "pre_checkout_query", filter);
  },
  purchased_paid_media(filter?: WebhookFilter) {
    return providerTrigger("telegram", "purchased_paid_media", filter);
  },
  removed_chat_boost(filter?: WebhookFilter) {
    return providerTrigger("telegram", "removed_chat_boost", filter);
  },
  shipping_query(filter?: WebhookFilter) {
    return providerTrigger("telegram", "shipping_query", filter);
  },
});
