// GENERATED by scripts/generate-triggers.mjs — do not edit.

import { providerTrigger } from "../provider-trigger.js";
import type { WebhookFilter } from "../triggers.js";

export const zendesk = Object.freeze({
  organization_created(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "organization.created", filter);
  },
  organization_deleted(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "organization.deleted", filter);
  },
  organization_updated(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "organization.updated", filter);
  },
  ticket_created(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "ticket.created", filter);
  },
  ticket_deleted(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "ticket.deleted", filter);
  },
  ticket_updated(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "ticket.updated", filter);
  },
  user_created(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "user.created", filter);
  },
  user_deleted(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "user.deleted", filter);
  },
  user_updated(filter?: WebhookFilter) {
    return providerTrigger("zendesk", "user.updated", filter);
  },
});
