import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { afterEach, expect, it, vi } from 'vitest';
import { checkAuthoredFlow } from '../src/cli/check.js';
import { canonicalize } from '../src/canonical.js';
import * as compiler from '../src/compile.js';
import { toKernelSpec } from '../src/compile.js';
import { validateSpecWithDaemon, type DaemonValidationDeps } from '../src/daemon-spec-validation.js';
import { RelayflowdNotFoundError, defaultRelayflowdPathDeps, resolveRelayflowdBinary } from '../src/relayflowd-path.js';
import { runCli } from '../src/cli.js';
import type { FlowSpec } from '../src/spec.js';

const flow: FlowSpec = { version: '0.1.0', steps: [
  { id: 'first', type: 'deterministic', command: 'echo hello', timeoutMs: 1000 },
  { id: 'second', type: 'deterministic', command: 'echo done' },
] };
const message = 'unknown field "timeout_ms" at steps[0] — refusing to guess (fail closed)';
const envelope = (error?: string) => ({ ok: error === undefined, protocol: 0, spec_version: '0.1.0',
  ...(error === undefined ? {} : { error: { code: 'invalid_spec', message: error } }) });
const deps = (error?: string): DaemonValidationDeps => ({ resolveBinary: () => '/stub/relayflowd',
  run: vi.fn(() => ({ status: error ? 2 : 0, stdout: JSON.stringify(envelope(error)), stderr: '' })) });
const roots: string[] = [];
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); roots.splice(0).forEach(p => rmSync(p, { recursive: true, force: true })); });

it('refuses package-valid daemon-invalid skew through check', () => {
  expect(checkAuthoredFlow(flow, '/tmp/flow.json').report.ok).toBe(true);
  const result = checkAuthoredFlow(flow, '/tmp/flow.json', undefined,
    { daemonValidation: 'auto', daemonValidationDeps: deps(message) });
  expect(result.report.ok).toBe(false);
  expect(result.report.diagnostics).toContainEqual({ severity: 'refusal', kind: 'invalid_spec',
    message, errors: [message], stepId: 'first' });
  expect(result.report.validation?.mode).toBe('daemon');
});

it('maps generated-step indices to submitted steps and identifies compiler bugs', () => {
  const gated: FlowSpec = { ...flow, steps: [{ ...flow.steps[0]!,
    verification: { type: 'artifact_exists', path: 'answer.txt' } }, flow.steps[1]!] };
  const result = validateSpecWithDaemon(gated, 'required', deps('unknown field "nope" at steps[1]'));
  expect(result.diagnostics[0]).toMatchObject({ stepId: 'first.gate', kind: 'invalid_spec' });
  expect(result.diagnostics[0]?.message).toContain('generated by this compiler');
  expect(result.diagnostics[0]?.message).toContain('Report this rather than editing the flow');
});

it('submits the canonical spec value used by run.start', () => {
  const transport = deps();
  expect(validateSpecWithDaemon(flow, 'required', transport).validation.mode).toBe('daemon');
  expect(transport.run).toHaveBeenCalledWith('/stub/relayflowd', canonicalize(toKernelSpec(flow)));
});

it('does not resolve or spawn in off mode or after local refusal', () => {
  const transport = { resolveBinary: vi.fn(), run: vi.fn() };
  expect(validateSpecWithDaemon(flow, 'off', transport).validation.reason).toBe('disabled');
  checkAuthoredFlow({ ...flow, steps: [] }, '/tmp/flow.json', undefined,
    { daemonValidation: 'required', daemonValidationDeps: transport });
  expect(transport.resolveBinary).not.toHaveBeenCalled();
  expect(transport.run).not.toHaveBeenCalled();
});

it.each(['auto', 'required'] as const)('handles absent and invalid explicit binaries in %s', mode => {
  for (const explicit of [false, true]) {
    const transport = { ...deps(), resolveBinary() {
      throw new RelayflowdNotFoundError(explicit ? 'RELAYFLOWD_BIN is invalid' : 'not found', explicit ? ['RELAYFLOWD_BIN=/bad'] : []);
    } };
    const result = validateSpecWithDaemon(flow, mode, transport);
    expect(result.validation.reason).toBe(explicit ? 'relayflowd_bin_invalid' : 'relayflowd_not_found');
    expect(result.diagnostics.length).toBe(mode === 'required' || explicit ? 1 : 0);
    if (mode === 'required') expect(result.diagnostics[0]?.severity).toBe('refusal');
    else if (explicit) expect(result.diagnostics[0]?.severity).toBe('warning');
  }
});

it.each([
  { status: 2, stdout: '', stderr: 'unrecognized subcommand', reason: 'no_verdict' },
  { status: 0, stdout: '{}', stderr: '', reason: 'no_verdict' },
  { status: null, stdout: '', stderr: '', error: Object.assign(new Error('timeout'), { code: 'ETIMEDOUT' }), reason: 'timed_out' },
  { status: null, stdout: '', stderr: '', error: new Error('spawn'), reason: 'spawn_failed' },
  { status: 0, stdout: JSON.stringify({ ...envelope(), protocol: 99 }), stderr: '', reason: 'protocol_mismatch' },
  { status: 2, stdout: JSON.stringify(envelope()), stderr: '', reason: 'abnormal_exit' },
  { status: null, signal: 'SIGTERM' as const, stdout: JSON.stringify(envelope()), stderr: '', reason: 'abnormal_exit' },
])('reports $reason without claiming daemon acceptance', outcome => {
  for (const mode of ['auto', 'required'] as const) {
    const result = validateSpecWithDaemon(flow, mode, { ...deps(), run: () => outcome });
    expect(result.validation).toMatchObject({ mode: 'local', reason: outcome.reason });
    expect(result.diagnostics[0]).toMatchObject({ severity: mode === 'auto' ? 'warning' : 'refusal' });
    expect(result.diagnostics[0]?.message).toContain('/stub/relayflowd');
    expect(result.diagnostics[0]?.message).toContain('acceptance is unproven');
  }
});

function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'daemon-check-')); roots.push(root);
  const binary = join(root, 'relayflowd');
  writeFileSync(binary, `#!${process.execPath}\nlet input='';process.stdin.on('data',x=>input+=x);process.stdin.on('end',()=>{const spec=JSON.parse(input);const bad=spec.steps.some(s=>s.timeout_ms);console.log(JSON.stringify(bad?${JSON.stringify(envelope(message))}:${JSON.stringify(envelope())}));process.exitCode=bad?2:0;});\n`, { mode: 0o755 });
  const path = join(root, 'flow.json'); writeFileSync(path, JSON.stringify(flow));
  return { root, binary, path };
}
function cli(path: string, binary: string, flags: string[] = []) {
  return spawnSync(process.execPath, [resolve('dist/cli.js'), 'check', ...flags, path], {
    encoding: 'utf8', env: { ...process.env, RELAYFLOWD_BIN: binary, FLOWS_NO_DAEMON_CHECK: '', FLOWS_CHECK_AGAINST_DAEMON: '' },
  });
}
it('real CLI refuses skew in auto and required modes', () => {
  const f = fixture();
  for (const flags of [[], ['--against-daemon']]) {
    const result = cli(f.path, f.binary, flags);
    expect(result.status).toBe(2);
    expect(result.stderr).toContain(`REFUSED [invalid_spec] ${message}`);
  }
});
it('keeps a daemon refusal whatever the validator exit status', () => {
  const result = validateSpecWithDaemon(flow, 'auto', { ...deps(),
    run: () => ({ status: null, signal: 'SIGTERM', stdout: JSON.stringify(envelope(message)), stderr: '' }) });
  expect(result.validation.mode).toBe('daemon');
  expect(result.diagnostics).toMatchObject([{ severity: 'refusal', kind: 'invalid_spec', stepId: 'first' }]);
});

it.each([['exit 2', 'process.exitCode=2'], ['SIGTERM', "process.kill(process.pid,'SIGTERM')"]])(
  'real CLI does not claim daemon acceptance after an accepting verdict then %s', (_label, ending) => {
    const f = fixture();
    writeFileSync(f.binary, `#!${process.execPath}\nprocess.stdin.resume();process.stdin.on('end',()=>{process.stdout.write(${JSON.stringify(JSON.stringify(envelope()) + '\n')},()=>{${ending};});});\n`, { mode: 0o755 });
    writeFileSync(f.path, JSON.stringify({ ...flow, steps: [{ id: 'a', type: 'deterministic', command: 'echo ok' }] }));
    const required = cli(f.path, f.binary, ['--against-daemon', '--json']);
    expect(required.status, required.stderr).toBe(2);
    expect(JSON.parse(required.stdout)).toMatchObject({ ok: false, validation: { mode: 'local', reason: 'abnormal_exit' } });
    const auto = cli(f.path, f.binary, ['--json']);
    expect(JSON.parse(auto.stdout)).toMatchObject({ validation: { mode: 'local', reason: 'abnormal_exit' },
      diagnostics: expect.arrayContaining([expect.objectContaining({ severity: 'warning', kind: 'daemon_unvalidated' })]) });
  });

it('real CLI labels daemon and offline passes, including JSON', () => {
  const f = fixture();
  expect(cli(f.path, f.binary, ['--no-daemon-check']).stdout).toContain('[local only: disabled');
  writeFileSync(f.path, JSON.stringify({ ...flow, steps: [{ id: 'a', type: 'deterministic', command: 'echo ok' }] }));
  const result = cli(f.path, f.binary);
  expect(result.status).toBe(0);
  expect(result.stdout).toContain(`[validated by relayflowd at ${f.binary}, protocol 0]`);
  expect(JSON.parse(cli(f.path, f.binary, ['--json']).stdout).validation.mode).toBe('daemon');
});
it('real CLI refuses an invalid RELAYFLOWD_BIN in required mode', () => {
  const f = fixture();
  const result = cli(f.path, join(f.root, 'missing'), ['--against-daemon']);
  expect(result.status).toBe(2);
  expect(result.stderr).toContain('REFUSED [daemon_validation_unavailable]');
  expect(result.stderr).toContain('RELAYFLOWD_BIN');
});
it('CLI refuses when no binary anchor exists in required mode', async () => {
  // Exercise the real resolver and CLI with deterministic absent anchors.
  vi.stubEnv('RELAYFLOWD_BIN', '');
  vi.spyOn(defaultRelayflowdPathDeps, 'isExecutable').mockReturnValue(false);
  vi.spyOn(defaultRelayflowdPathDeps, 'resolveFrom').mockReturnValue(null);
  vi.spyOn(defaultRelayflowdPathDeps, 'which').mockReturnValue(null);
  expect(() => resolveRelayflowdBinary()).toThrow(RelayflowdNotFoundError);
  const f = fixture(); const stderr: string[] = [];
  expect(await runCli(['check', '--against-daemon', f.path], { stdout: () => {}, stderr: s => stderr.push(s) })).toBe(2);
  expect(stderr.join('\n')).toContain('REFUSED [daemon_validation_unavailable]');
});
it('flags win over environment and are check-only and mutually exclusive', async () => {
  const f = fixture(); vi.stubEnv('RELAYFLOWD_BIN', f.binary); vi.stubEnv('FLOWS_CHECK_AGAINST_DAEMON', '1');
  const io = { stdout: vi.fn(), stderr: vi.fn() };
  expect(await runCli(['check', '--no-daemon-check', f.path], io)).toBe(0);
  for (const args of [['check', '--against-daemon', '--no-daemon-check', f.path],
    ['run', '--against-daemon', f.path], ['resume', '--no-daemon-check', 'run-id']]) {
    expect(await runCli(args, io)).toBe(2);
  }
});

it('fails closed if kernel lowering throws after local preflight passes', () => {
  vi.spyOn(compiler, 'toKernelSpec').mockImplementation(() => {
    throw new compiler.CompileError(['cannot lower this declaration']);
  });
  const transport = deps();
  const checked = checkAuthoredFlow(flow, '/tmp/flow.json', undefined,
    { daemonValidation: 'auto', daemonValidationDeps: transport });
  expect(checked.report.ok).toBe(false);
  expect(checked.report.diagnostics).toContainEqual({ severity: 'refusal', kind: 'invalid_spec',
    message: 'cannot lower this declaration', errors: ['cannot lower this declaration'] });
  expect(transport.run).not.toHaveBeenCalled();
});

it('refuses agent cwd skew accepted by package preflight', () => {
  const agent: FlowSpec = { version: '0.1.0', steps: [{ id: 'edit', type: 'agent',
    cli: resolve('../../testdata/preflight/authenticated-cli'), instruction: 'edit', cwd: 'worktree' }] };
  const refusal = 'unknown field "cwd" at steps[0] — refusing to guess (fail closed)';
  expect(checkAuthoredFlow(agent, '/tmp/flow.json').report.ok).toBe(true);
  const checked = checkAuthoredFlow(agent, '/tmp/flow.json', undefined,
    { daemonValidation: 'required', daemonValidationDeps: deps(refusal) });
  expect(checked.report.ok).toBe(false);
  expect(checked.report.diagnostics).toContainEqual({ severity: 'refusal', kind: 'invalid_spec',
    message: refusal, errors: [refusal], stepId: 'edit' });
});

it('maps authored steps following generated steps without blaming the compiler', () => {
  const gated: FlowSpec = { ...flow, steps: [{ ...flow.steps[0]!,
    verification: { type: 'artifact_exists', path: 'answer.txt' } }, flow.steps[1]!] };
  const checked = checkAuthoredFlow(gated, '/tmp/flow.json', undefined,
    { daemonValidation: 'required', daemonValidationDeps: deps('unknown field "nope" at steps[2]') });
  expect(checked.report.ok).toBe(false);
  expect(checked.report.diagnostics).toContainEqual({ severity: 'refusal', kind: 'invalid_spec',
    message: 'unknown field "nope" at steps[2]', errors: ['unknown field "nope" at steps[2]'], stepId: 'second' });
});

it('memoizes binary discovery without memoizing validation verdicts', async () => {
  vi.stubEnv('RELAYFLOWD_BIN', '');
  vi.stubEnv('PATH', '/missing/check-discovery');
  vi.spyOn(defaultRelayflowdPathDeps, 'isExecutable').mockReturnValue(false);
  vi.spyOn(defaultRelayflowdPathDeps, 'resolveFrom').mockReturnValue(null);
  const which = vi.spyOn(defaultRelayflowdPathDeps, 'which').mockReturnValue(null);
  const f = fixture();
  const io = { stdout: vi.fn(), stderr: vi.fn() };
  // The local command probe needs a real absolute executable with this PATH.
  writeFileSync(f.path, JSON.stringify({ ...flow, steps: [{ id: 'a', type: 'deterministic', command: '/bin/echo ok' }] }));
  await runCli(['check', '--against-daemon', f.path], io);
  await runCli(['check', '--against-daemon', f.path], io);
  expect(which).toHaveBeenCalledTimes(1);
  const transport = deps();
  validateSpecWithDaemon(flow, 'auto', transport);
  validateSpecWithDaemon(flow, 'auto', transport);
  expect(transport.run).toHaveBeenCalledTimes(2);
});
