import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

const surface = fileURLToPath(new URL('../packages/surface/', import.meta.url));
const require = createRequire(join(surface, 'package.json'));
const ts = require('typescript');
const { values } = parseArgs({ options: {
  'out-dir': { type: 'string', default: join(surface, 'src/helpers') },
  'adapters-dir': { type: 'string' },
} });
// The pinned published declaration makes regeneration reproducible in CI.
// An explicit checkout lets adapter authors check source changes before release.
const input = values['adapters-dir']
  ? join(resolve(values['adapters-dir']), 'packages/relay-helpers/src/slack.ts')
  : join(dirname(require.resolve('@relayfile/relay-helpers/package.json')), 'dist/slack.d.ts');
const source = ts.createSourceFile(input, readFileSync(input, 'utf8'), ts.ScriptTarget.Latest, true);
assert.equal(source.parseDiagnostics.length, 0, 'Invalid Slack adapter source');
const client = source.statements.find(node => ts.isInterfaceDeclaration(node) && node.name.text === 'SlackClient');
assert(client, 'Missing upstream SlackClient interface');
const verbs = ['post', 'dm', 'reply', 'react'];
assert.deepEqual(client.members.map(member => member.name?.getText(source)), verbs,
  'Slack adapter verbs changed; review dispatcher support before regenerating');
const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true });
const methods = client.members.map(member => {
  assert(ts.isMethodSignature(member) && !member.typeParameters?.length,
    'Expected a non-generic Slack method');
  // Copy the parameter AST unchanged: no hand-maintained approximation of args.
  const parameters = member.parameters.map(parameter =>
    printer.printNode(ts.EmitHint.Unspecified, parameter, source)).join(', ');
  const name = member.name.getText(source);
  return `  ${name}(${parameters}): ReturnType<RuntimeSlackHelper["${name}"]>;`.replaceAll('\n', '\n  ');
});
const header = '// GENERATED by scripts/generate-helpers.mjs — do not edit.\n'
  + '// Run `npm run gen --prefix packages/surface` from the repository root.\n';
const files = {
  'slack.ts': `${header}\nimport type { SlackHelper as RuntimeSlackHelper } from "../slack.js";\n\n`
    + '/** Adapter argument shapes over the journal-backed Slack dispatcher. */\n'
    + `export interface SlackHelper {\n${methods.join('\n')}\n}\n`,
  'index.ts': `${header}\nimport type { SlackHelper } from "./slack.js";\n\n`
    + 'export type { SlackHelper } from "./slack.js";\n\n'
    + '/** Supported helper namespaces composed into Ctx. */\n'
    + 'export interface Helpers {\n  slack: SlackHelper;\n}\n',
};
const destination = resolve(values['out-dir']);
mkdirSync(destination, { recursive: true });
for (const [name, content] of Object.entries(files)) writeFileSync(join(destination, name), content);
console.log(`Generated ${Object.keys(files).join(', ')}`);
