import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

const surface = fileURLToPath(new URL('../packages/surface/', import.meta.url));
const require = createRequire(join(surface, 'package.json'));
const ts = require('typescript');
const upstream = require('@relayfile/relay-helpers');
const { WRITEBACK_PATH_CATALOG: catalog, ADAPTERS_WITHOUT_WRITEBACK_PATHS: missing } = require('@relayfile/adapter-core/writeback-paths');
const { values } = parseArgs({ options: {
  'out-dir': { type: 'string', default: join(surface, 'src/helpers') },
  'adapters-dir': { type: 'string' },
} });
const names = new Set([...Object.keys(catalog), ...missing.map(item => item.provider), 'webhook-server']);
if (values['adapters-dir']) {
  const packages = join(resolve(values['adapters-dir']), 'packages');
  for (const entry of readdirSync(packages, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const pkg = JSON.parse(readFileSync(join(packages, entry.name, 'package.json'), 'utf8'));
    if (pkg.name.startsWith('@relayfile/adapter-') && entry.name !== 'core') names.add(entry.name);
  }
}
const camel = name => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const title = name => camel(name).replace(/^./, c => c.toUpperCase());
const header = '// GENERATED by scripts/generate-helpers.mjs — do not edit.\n'
  + '// Run `npm run gen --prefix packages/surface` from the repository root.\n';
const destination = resolve(values['out-dir']);
mkdirSync(destination, { recursive: true });
const files = {};
// Keep Slack's established receipt and argument contract, copied from its AST.
const slackSource = join(dirname(require.resolve('@relayfile/relay-helpers/package.json')), 'dist/slack.d.ts');
const source = ts.createSourceFile(slackSource, readFileSync(slackSource, 'utf8'), ts.ScriptTarget.Latest, true);
const slack = source.statements.find(node => ts.isInterfaceDeclaration(node) && node.name.text === 'SlackClient');
assert(slack, 'Missing upstream SlackClient interface');
assert.deepEqual(slack.members.map(member => member.name?.getText(source)), ['post', 'dm', 'reply', 'react']);
const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true });
const methods = slack.members.map(member => {
  const name = member.name.getText(source);
  // The surface adds structured posts while the pinned adapter accepts text only.
  if (name === 'post') return '  post(...args: Parameters<RuntimeSlackHelper["post"]>): ReturnType<RuntimeSlackHelper["post"]>;';
  const params = member.parameters.map(p => printer.printNode(ts.EmitHint.Unspecified, p, source)).join(', ');
  return `  ${name}(${params}): ReturnType<RuntimeSlackHelper["${name}"]>;`.replaceAll('\n', '\n  ');
});
// Pinned OpenAPI fragments fill the gap until relay-helpers exports message types.
// Slack's schema deliberately leaves block contents and attachment fields open.
const messageSchema = JSON.parse(readFileSync(new URL('./slack-message-schema.json', import.meta.url), 'utf8'));
function schemaType(schema) {
  if (schema.type === 'string') return 'string';
  assert.equal(schema.type, 'object', 'Unsupported Slack schema type');
  const fields = Object.entries(schema.properties ?? {}).map(([name, value]) =>
    `${name}${schema.required?.includes(name) ? '' : '?'}: ${schemaType(value)};`);
  if (schema.additionalProperties !== false) fields.push('[key: string]: unknown;');
  return `{ ${fields.join(' ')} }`;
}
const messageTypes = Object.entries(messageSchema.schemas).map(([name, { schema }]) =>
  `export type ${name} = ${schemaType(schema)};`).join('\n');
files['slack.ts'] = `${header}\nimport type { SlackHelper as RuntimeSlackHelper } from "../slack.js";\n\n`
  + '/** Generated from the pinned Slack OpenAPI fragments in scripts/slack-message-schema.json. */\n'
  + `${messageTypes}\n\n`
  + '/** Adapter argument shapes over the journal-backed Slack dispatcher. */\n'
  + `export interface SlackHelper {\n${methods.join('\n')}\n}\n`;
const providers = [...names].sort();
for (const provider of providers.filter(p => p !== 'slack')) {
  const factory = `${camel(provider)}Client`;
  const supported = catalog[provider] !== undefined;
  const special = ['github', 'notion', 'stripe'].includes(provider);
  files[`${provider}.ts`] = header + '\n'
    + (special ? `import { ${factory} } from "../helper-clients.js";\n`
      : typeof upstream[factory] === 'function' ? `import { ${factory} } from "@relayfile/relay-helpers";\n`
      : supported ? `import { providerClient } from "@relayfile/relay-helpers";\nimport type { RelayClientOptions } from "@relayfile/relay-helpers/transport";\nconst ${factory} = (options: RelayClientOptions) => providerClient("${provider}", options);\n` : '')
    + `import { bindHelper, type EffectDispatcher, type JournalHelper${!supported && !special ? ', type UnavailableHelper' : ''} } from "../effect-transport.js";\n\n`
    + `export type ${title(provider)}Helper = ${supported || special ? `JournalHelper<ReturnType<typeof ${factory}>>` : 'UnavailableHelper'};\n\n`
    + `export const create${title(provider)}Helper = (dispatch: EffectDispatcher): ${title(provider)}Helper =>\n`
    + `  bindHelper(${JSON.stringify(provider)}, ${supported || special ? factory : 'undefined'}, dispatch);\n`;
}
files['index.ts'] = header + '\nimport type { SlackHelper } from "./slack.js";\n'
  + providers.filter(p => p !== 'slack').map(p => `import { create${title(p)}Helper, type ${title(p)}Helper } from "./${p}.js";`).join('\n')
  + '\nimport type { EffectDispatcher } from "../effect-transport.js";\n\n'
  + providers.map(p => `export type { ${title(p)}Helper } from "./${p}.js";`).join('\n')
  + '\n\nexport interface Helpers {\n' + providers.map(p => `  ${camel(p)}: ${title(p)}Helper;`).join('\n') + '\n}\n\n'
  + 'export function createHelpers(dispatch: EffectDispatcher): Omit<Helpers, "slack"> {\n  return {\n'
  + providers.filter(p => p !== 'slack').map(p => `    ${camel(p)}: create${title(p)}Helper(dispatch),`).join('\n') + '\n  };\n}\n';
files['clients.ts'] = header + '\nimport * as upstream from "@relayfile/relay-helpers";\nimport * as custom from "../helper-clients.js";\nimport type { HelperFactory } from "../effect-transport.js";\n\nexport const helperClients: Readonly<Record<string, HelperFactory>> = {\n'
  + providers.filter(p => p !== 'slack' && (p === 'stripe' || catalog[p])).map(p => `  "${p}": ${['github', 'notion', 'stripe'].includes(p) ? `custom.${camel(p)}Client` : typeof upstream[`${camel(p)}Client`] === 'function' ? `upstream.${camel(p)}Client` : `(options) => upstream.providerClient("${p}", options)`},`).join('\n') + '\n};\n';
files['providers.ts'] = header + '\nexport const helperProviders = ' + JSON.stringify(providers.map(p => ({
  provider: p, namespace: camel(p), mockEnv: `RELAYFLOWS_${p.replaceAll('-', '_').toUpperCase()}_MOCK`,
  supported: p === 'stripe' || catalog[p] !== undefined,
})), null, 2) + ' as const;\n';
for (const [name, content] of Object.entries(files)) writeFileSync(join(destination, name), content);
console.log(`Generated ${providers.length} provider helpers (${providers.filter(p => !catalog[p] && p !== 'stripe').length} without upstream writeback clients)`);
