// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { bindHelper, type EffectDispatcher, type JournalHelper, type UnavailableHelper } from "../effect-transport.js";

export type AirtableHelper = UnavailableHelper;

export const createAirtableHelper = (dispatch: EffectDispatcher): AirtableHelper =>
  bindHelper("airtable", undefined, dispatch);
