// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { asanaClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type AsanaHelper = JournalHelper<ReturnType<typeof asanaClient>>;

export const createAsanaHelper = (dispatch: EffectDispatcher): AsanaHelper =>
  bindHelper("asana", asanaClient, dispatch);
