// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { azureBlobClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type AzureBlobHelper = JournalHelper<ReturnType<typeof azureBlobClient>>;

export const createAzureBlobHelper = (dispatch: EffectDispatcher): AzureBlobHelper =>
  bindHelper("azure-blob", azureBlobClient, dispatch);
