// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { boxClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type BoxHelper = JournalHelper<ReturnType<typeof boxClient>>;

export const createBoxHelper = (dispatch: EffectDispatcher): BoxHelper =>
  bindHelper("box", boxClient, dispatch);
