// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { calendlyClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type CalendlyHelper = JournalHelper<ReturnType<typeof calendlyClient>>;

export const createCalendlyHelper = (dispatch: EffectDispatcher): CalendlyHelper =>
  bindHelper("calendly", calendlyClient, dispatch);
