// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { clickupClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type ClickupHelper = JournalHelper<ReturnType<typeof clickupClient>>;

export const createClickupHelper = (dispatch: EffectDispatcher): ClickupHelper =>
  bindHelper("clickup", clickupClient, dispatch);
