// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import * as upstream from "@relayfile/relay-helpers";
import * as custom from "../helper-clients.js";
import type { HelperFactory } from "../effect-transport.js";

export const helperClients: Readonly<Record<string, HelperFactory>> = {
  "asana": upstream.asanaClient,
  "azure-blob": upstream.azureBlobClient,
  "box": upstream.boxClient,
  "calendly": upstream.calendlyClient,
  "clickup": upstream.clickupClient,
  "cloudflare": upstream.cloudflareClient,
  "confluence": upstream.confluenceClient,
  "daytona": upstream.daytonaClient,
  "dropbox": upstream.dropboxClient,
  "gcs": upstream.gcsClient,
  "github": custom.githubClient,
  "gitlab": upstream.gitlabClient,
  "gmail": upstream.gmailClient,
  "google-calendar": upstream.googleCalendarClient,
  "google-drive": upstream.googleDriveClient,
  "granola": upstream.granolaClient,
  "hubspot": upstream.hubspotClient,
  "intercom": upstream.intercomClient,
  "jira": upstream.jiraClient,
  "linear": upstream.linearClient,
  "mailgun": upstream.mailgunClient,
  "mixpanel": upstream.mixpanelClient,
  "notion": custom.notionClient,
  "onedrive": upstream.onedriveClient,
  "pipedrive": upstream.pipedriveClient,
  "postgres": upstream.postgresClient,
  "ramp": (options) => upstream.providerClient("ramp", options),
  "recall": upstream.recallClient,
  "reddit": upstream.redditClient,
  "redis": upstream.redisClient,
  "s3": upstream.s3Client,
  "salesforce": upstream.salesforceClient,
  "sendgrid": upstream.sendgridClient,
  "sharepoint": upstream.sharepointClient,
  "shortcut": upstream.shortcutClient,
  "stripe": custom.stripeClient,
  "teams": upstream.teamsClient,
  "telegram": upstream.telegramClient,
  "zendesk": upstream.zendeskClient,
};
