// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { cloudflareClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type CloudflareHelper = JournalHelper<ReturnType<typeof cloudflareClient>>;

export const createCloudflareHelper = (dispatch: EffectDispatcher): CloudflareHelper =>
  bindHelper("cloudflare", cloudflareClient, dispatch);
