// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { confluenceClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type ConfluenceHelper = JournalHelper<ReturnType<typeof confluenceClient>>;

export const createConfluenceHelper = (dispatch: EffectDispatcher): ConfluenceHelper =>
  bindHelper("confluence", confluenceClient, dispatch);
