// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { daytonaClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type DaytonaHelper = JournalHelper<ReturnType<typeof daytonaClient>>;

export const createDaytonaHelper = (dispatch: EffectDispatcher): DaytonaHelper =>
  bindHelper("daytona", daytonaClient, dispatch);
