// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { dropboxClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type DropboxHelper = JournalHelper<ReturnType<typeof dropboxClient>>;

export const createDropboxHelper = (dispatch: EffectDispatcher): DropboxHelper =>
  bindHelper("dropbox", dropboxClient, dispatch);
