// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { gcsClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GcsHelper = JournalHelper<ReturnType<typeof gcsClient>>;

export const createGcsHelper = (dispatch: EffectDispatcher): GcsHelper =>
  bindHelper("gcs", gcsClient, dispatch);
