// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { githubClient } from "../helper-clients.js";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GithubHelper = JournalHelper<ReturnType<typeof githubClient>>;

export const createGithubHelper = (dispatch: EffectDispatcher): GithubHelper =>
  bindHelper("github", githubClient, dispatch);
