// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { gitlabClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GitlabHelper = JournalHelper<ReturnType<typeof gitlabClient>>;

export const createGitlabHelper = (dispatch: EffectDispatcher): GitlabHelper =>
  bindHelper("gitlab", gitlabClient, dispatch);
