// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { gmailClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GmailHelper = JournalHelper<ReturnType<typeof gmailClient>>;

export const createGmailHelper = (dispatch: EffectDispatcher): GmailHelper =>
  bindHelper("gmail", gmailClient, dispatch);
