// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { googleDriveClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GoogleDriveHelper = JournalHelper<ReturnType<typeof googleDriveClient>>;

export const createGoogleDriveHelper = (dispatch: EffectDispatcher): GoogleDriveHelper =>
  bindHelper("google-drive", googleDriveClient, dispatch);
