// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { googleCalendarClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GoogleCalendarHelper = JournalHelper<ReturnType<typeof googleCalendarClient>>;

export const createGoogleCalendarHelper = (dispatch: EffectDispatcher): GoogleCalendarHelper =>
  bindHelper("google-calendar", googleCalendarClient, dispatch);
