// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { granolaClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type GranolaHelper = JournalHelper<ReturnType<typeof granolaClient>>;

export const createGranolaHelper = (dispatch: EffectDispatcher): GranolaHelper =>
  bindHelper("granola", granolaClient, dispatch);
