// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { hubspotClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type HubspotHelper = JournalHelper<ReturnType<typeof hubspotClient>>;

export const createHubspotHelper = (dispatch: EffectDispatcher): HubspotHelper =>
  bindHelper("hubspot", hubspotClient, dispatch);
