// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import type { SlackHelper } from "./slack.js";

export type { SlackHelper } from "./slack.js";

/** Supported helper namespaces composed into Ctx. */
export interface Helpers {
  slack: SlackHelper;
}
