// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { intercomClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type IntercomHelper = JournalHelper<ReturnType<typeof intercomClient>>;

export const createIntercomHelper = (dispatch: EffectDispatcher): IntercomHelper =>
  bindHelper("intercom", intercomClient, dispatch);
