// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { jiraClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type JiraHelper = JournalHelper<ReturnType<typeof jiraClient>>;

export const createJiraHelper = (dispatch: EffectDispatcher): JiraHelper =>
  bindHelper("jira", jiraClient, dispatch);
