// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { linearClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type LinearHelper = JournalHelper<ReturnType<typeof linearClient>>;

export const createLinearHelper = (dispatch: EffectDispatcher): LinearHelper =>
  bindHelper("linear", linearClient, dispatch);
