// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { mailgunClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type MailgunHelper = JournalHelper<ReturnType<typeof mailgunClient>>;

export const createMailgunHelper = (dispatch: EffectDispatcher): MailgunHelper =>
  bindHelper("mailgun", mailgunClient, dispatch);
