// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { mixpanelClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type MixpanelHelper = JournalHelper<ReturnType<typeof mixpanelClient>>;

export const createMixpanelHelper = (dispatch: EffectDispatcher): MixpanelHelper =>
  bindHelper("mixpanel", mixpanelClient, dispatch);
