// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { notionClient } from "../helper-clients.js";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type NotionHelper = JournalHelper<ReturnType<typeof notionClient>>;

export const createNotionHelper = (dispatch: EffectDispatcher): NotionHelper =>
  bindHelper("notion", notionClient, dispatch);
