// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { onedriveClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type OnedriveHelper = JournalHelper<ReturnType<typeof onedriveClient>>;

export const createOnedriveHelper = (dispatch: EffectDispatcher): OnedriveHelper =>
  bindHelper("onedrive", onedriveClient, dispatch);
