// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { pipedriveClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type PipedriveHelper = JournalHelper<ReturnType<typeof pipedriveClient>>;

export const createPipedriveHelper = (dispatch: EffectDispatcher): PipedriveHelper =>
  bindHelper("pipedrive", pipedriveClient, dispatch);
