// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { postgresClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type PostgresHelper = JournalHelper<ReturnType<typeof postgresClient>>;

export const createPostgresHelper = (dispatch: EffectDispatcher): PostgresHelper =>
  bindHelper("postgres", postgresClient, dispatch);
