// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

export const helperProviders = [
  {
    "provider": "airtable",
    "namespace": "airtable",
    "mockEnv": "RELAYFLOWS_AIRTABLE_MOCK",
    "supported": false
  },
  {
    "provider": "asana",
    "namespace": "asana",
    "mockEnv": "RELAYFLOWS_ASANA_MOCK",
    "supported": true
  },
  {
    "provider": "azure-blob",
    "namespace": "azureBlob",
    "mockEnv": "RELAYFLOWS_AZURE_BLOB_MOCK",
    "supported": true
  },
  {
    "provider": "box",
    "namespace": "box",
    "mockEnv": "RELAYFLOWS_BOX_MOCK",
    "supported": true
  },
  {
    "provider": "calendly",
    "namespace": "calendly",
    "mockEnv": "RELAYFLOWS_CALENDLY_MOCK",
    "supported": true
  },
  {
    "provider": "clickup",
    "namespace": "clickup",
    "mockEnv": "RELAYFLOWS_CLICKUP_MOCK",
    "supported": true
  },
  {
    "provider": "cloudflare",
    "namespace": "cloudflare",
    "mockEnv": "RELAYFLOWS_CLOUDFLARE_MOCK",
    "supported": true
  },
  {
    "provider": "confluence",
    "namespace": "confluence",
    "mockEnv": "RELAYFLOWS_CONFLUENCE_MOCK",
    "supported": true
  },
  {
    "provider": "daytona",
    "namespace": "daytona",
    "mockEnv": "RELAYFLOWS_DAYTONA_MOCK",
    "supported": true
  },
  {
    "provider": "docker-hub",
    "namespace": "dockerHub",
    "mockEnv": "RELAYFLOWS_DOCKER_HUB_MOCK",
    "supported": false
  },
  {
    "provider": "dropbox",
    "namespace": "dropbox",
    "mockEnv": "RELAYFLOWS_DROPBOX_MOCK",
    "supported": true
  },
  {
    "provider": "fathom",
    "namespace": "fathom",
    "mockEnv": "RELAYFLOWS_FATHOM_MOCK",
    "supported": false
  },
  {
    "provider": "gcp",
    "namespace": "gcp",
    "mockEnv": "RELAYFLOWS_GCP_MOCK",
    "supported": false
  },
  {
    "provider": "gcs",
    "namespace": "gcs",
    "mockEnv": "RELAYFLOWS_GCS_MOCK",
    "supported": true
  },
  {
    "provider": "github",
    "namespace": "github",
    "mockEnv": "RELAYFLOWS_GITHUB_MOCK",
    "supported": true
  },
  {
    "provider": "gitlab",
    "namespace": "gitlab",
    "mockEnv": "RELAYFLOWS_GITLAB_MOCK",
    "supported": true
  },
  {
    "provider": "gmail",
    "namespace": "gmail",
    "mockEnv": "RELAYFLOWS_GMAIL_MOCK",
    "supported": true
  },
  {
    "provider": "google-calendar",
    "namespace": "googleCalendar",
    "mockEnv": "RELAYFLOWS_GOOGLE_CALENDAR_MOCK",
    "supported": true
  },
  {
    "provider": "google-drive",
    "namespace": "googleDrive",
    "mockEnv": "RELAYFLOWS_GOOGLE_DRIVE_MOCK",
    "supported": true
  },
  {
    "provider": "granola",
    "namespace": "granola",
    "mockEnv": "RELAYFLOWS_GRANOLA_MOCK",
    "supported": true
  },
  {
    "provider": "hubspot",
    "namespace": "hubspot",
    "mockEnv": "RELAYFLOWS_HUBSPOT_MOCK",
    "supported": true
  },
  {
    "provider": "intercom",
    "namespace": "intercom",
    "mockEnv": "RELAYFLOWS_INTERCOM_MOCK",
    "supported": true
  },
  {
    "provider": "jira",
    "namespace": "jira",
    "mockEnv": "RELAYFLOWS_JIRA_MOCK",
    "supported": true
  },
  {
    "provider": "linear",
    "namespace": "linear",
    "mockEnv": "RELAYFLOWS_LINEAR_MOCK",
    "supported": true
  },
  {
    "provider": "mailgun",
    "namespace": "mailgun",
    "mockEnv": "RELAYFLOWS_MAILGUN_MOCK",
    "supported": true
  },
  {
    "provider": "mixpanel",
    "namespace": "mixpanel",
    "mockEnv": "RELAYFLOWS_MIXPANEL_MOCK",
    "supported": true
  },
  {
    "provider": "neon",
    "namespace": "neon",
    "mockEnv": "RELAYFLOWS_NEON_MOCK",
    "supported": false
  },
  {
    "provider": "notion",
    "namespace": "notion",
    "mockEnv": "RELAYFLOWS_NOTION_MOCK",
    "supported": true
  },
  {
    "provider": "onedrive",
    "namespace": "onedrive",
    "mockEnv": "RELAYFLOWS_ONEDRIVE_MOCK",
    "supported": true
  },
  {
    "provider": "pipedrive",
    "namespace": "pipedrive",
    "mockEnv": "RELAYFLOWS_PIPEDRIVE_MOCK",
    "supported": true
  },
  {
    "provider": "postgres",
    "namespace": "postgres",
    "mockEnv": "RELAYFLOWS_POSTGRES_MOCK",
    "supported": true
  },
  {
    "provider": "posthog",
    "namespace": "posthog",
    "mockEnv": "RELAYFLOWS_POSTHOG_MOCK",
    "supported": false
  },
  {
    "provider": "ramp",
    "namespace": "ramp",
    "mockEnv": "RELAYFLOWS_RAMP_MOCK",
    "supported": true
  },
  {
    "provider": "recall",
    "namespace": "recall",
    "mockEnv": "RELAYFLOWS_RECALL_MOCK",
    "supported": true
  },
  {
    "provider": "reddit",
    "namespace": "reddit",
    "mockEnv": "RELAYFLOWS_REDDIT_MOCK",
    "supported": true
  },
  {
    "provider": "redis",
    "namespace": "redis",
    "mockEnv": "RELAYFLOWS_REDIS_MOCK",
    "supported": true
  },
  {
    "provider": "s3",
    "namespace": "s3",
    "mockEnv": "RELAYFLOWS_S3_MOCK",
    "supported": true
  },
  {
    "provider": "salesforce",
    "namespace": "salesforce",
    "mockEnv": "RELAYFLOWS_SALESFORCE_MOCK",
    "supported": true
  },
  {
    "provider": "segment",
    "namespace": "segment",
    "mockEnv": "RELAYFLOWS_SEGMENT_MOCK",
    "supported": false
  },
  {
    "provider": "sendgrid",
    "namespace": "sendgrid",
    "mockEnv": "RELAYFLOWS_SENDGRID_MOCK",
    "supported": true
  },
  {
    "provider": "sharepoint",
    "namespace": "sharepoint",
    "mockEnv": "RELAYFLOWS_SHAREPOINT_MOCK",
    "supported": true
  },
  {
    "provider": "shopify",
    "namespace": "shopify",
    "mockEnv": "RELAYFLOWS_SHOPIFY_MOCK",
    "supported": false
  },
  {
    "provider": "shortcut",
    "namespace": "shortcut",
    "mockEnv": "RELAYFLOWS_SHORTCUT_MOCK",
    "supported": true
  },
  {
    "provider": "slack",
    "namespace": "slack",
    "mockEnv": "RELAYFLOWS_SLACK_MOCK",
    "supported": true
  },
  {
    "provider": "stripe",
    "namespace": "stripe",
    "mockEnv": "RELAYFLOWS_STRIPE_MOCK",
    "supported": true
  },
  {
    "provider": "teams",
    "namespace": "teams",
    "mockEnv": "RELAYFLOWS_TEAMS_MOCK",
    "supported": true
  },
  {
    "provider": "telegram",
    "namespace": "telegram",
    "mockEnv": "RELAYFLOWS_TELEGRAM_MOCK",
    "supported": true
  },
  {
    "provider": "webhook-server",
    "namespace": "webhookServer",
    "mockEnv": "RELAYFLOWS_WEBHOOK_SERVER_MOCK",
    "supported": false
  },
  {
    "provider": "x",
    "namespace": "x",
    "mockEnv": "RELAYFLOWS_X_MOCK",
    "supported": false
  },
  {
    "provider": "zendesk",
    "namespace": "zendesk",
    "mockEnv": "RELAYFLOWS_ZENDESK_MOCK",
    "supported": true
  }
] as const;
