// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

// `supported: true` designates a client whose catalog resources dispatch;
// it is not a claim of exhaustive vendor API coverage. `"partial"` marks a
// client that is usable for `resources` but is known to omit workflows its
// namespace suggests — see `note`. `false` means no upstream writeback client.
export const helperProviders = [
  {
    "provider": "airtable",
    "namespace": "airtable",
    "mockEnv": "RELAYFLOWS_AIRTABLE_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "asana",
    "namespace": "asana",
    "mockEnv": "RELAYFLOWS_ASANA_MOCK",
    "supported": true,
    "resources": [
      "projects",
      "sections",
      "tasks"
    ]
  },
  {
    "provider": "azure-blob",
    "namespace": "azureBlob",
    "mockEnv": "RELAYFLOWS_AZURE_BLOB_MOCK",
    "supported": true,
    "resources": [
      "blobs",
      "event-subscriptions"
    ]
  },
  {
    "provider": "box",
    "namespace": "box",
    "mockEnv": "RELAYFLOWS_BOX_MOCK",
    "supported": true,
    "resources": [
      "files",
      "webhooks"
    ]
  },
  {
    "provider": "calendly",
    "namespace": "calendly",
    "mockEnv": "RELAYFLOWS_CALENDLY_MOCK",
    "supported": true,
    "resources": [
      "event-types",
      "invitees",
      "scheduled-events"
    ]
  },
  {
    "provider": "clickup",
    "namespace": "clickup",
    "mockEnv": "RELAYFLOWS_CLICKUP_MOCK",
    "supported": true,
    "resources": [
      "comments",
      "folders",
      "lists",
      "tasks"
    ]
  },
  {
    "provider": "cloudflare",
    "namespace": "cloudflare",
    "mockEnv": "RELAYFLOWS_CLOUDFLARE_MOCK",
    "supported": true,
    "resources": [
      "d1-databases",
      "dns-records",
      "kv-namespaces",
      "notification-events",
      "notification-policies",
      "notification-webhooks",
      "pages-projects",
      "queues",
      "r2-buckets",
      "tunnels",
      "worker-usage",
      "workers-scripts",
      "zones"
    ]
  },
  {
    "provider": "confluence",
    "namespace": "confluence",
    "mockEnv": "RELAYFLOWS_CONFLUENCE_MOCK",
    "supported": true,
    "resources": [
      "pages"
    ]
  },
  {
    "provider": "daytona",
    "namespace": "daytona",
    "mockEnv": "RELAYFLOWS_DAYTONA_MOCK",
    "supported": true,
    "resources": [
      "usage"
    ]
  },
  {
    "provider": "docker-hub",
    "namespace": "dockerHub",
    "mockEnv": "RELAYFLOWS_DOCKER_HUB_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "dropbox",
    "namespace": "dropbox",
    "mockEnv": "RELAYFLOWS_DROPBOX_MOCK",
    "supported": true,
    "resources": [
      "cursors",
      "files",
      "folders",
      "shared-folders",
      "shared-links"
    ]
  },
  {
    "provider": "fathom",
    "namespace": "fathom",
    "mockEnv": "RELAYFLOWS_FATHOM_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "gcp",
    "namespace": "gcp",
    "mockEnv": "RELAYFLOWS_GCP_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "gcs",
    "namespace": "gcs",
    "mockEnv": "RELAYFLOWS_GCS_MOCK",
    "supported": true,
    "resources": [
      "notifications",
      "objects"
    ]
  },
  {
    "provider": "github",
    "namespace": "github",
    "mockEnv": "RELAYFLOWS_GITHUB_MOCK",
    "supported": true,
    "resources": [
      "close-pull-request",
      "issue-comments",
      "issues",
      "merge",
      "pull-requests",
      "refs",
      "replies",
      "reviews"
    ]
  },
  {
    "provider": "gitlab",
    "namespace": "gitlab",
    "mockEnv": "RELAYFLOWS_GITLAB_MOCK",
    "supported": "partial",
    "resources": [
      "comments",
      "discussions"
    ],
    "note": "Comments and discussions only. Issue list/read/create and merge-request list/read/create are unavailable through f.gitlab."
  },
  {
    "provider": "gmail",
    "namespace": "gmail",
    "mockEnv": "RELAYFLOWS_GMAIL_MOCK",
    "supported": true,
    "resources": [
      "drafts",
      "threads",
      "watches"
    ]
  },
  {
    "provider": "google-calendar",
    "namespace": "googleCalendar",
    "mockEnv": "RELAYFLOWS_GOOGLE_CALENDAR_MOCK",
    "supported": true,
    "resources": [
      "events"
    ]
  },
  {
    "provider": "google-drive",
    "namespace": "googleDrive",
    "mockEnv": "RELAYFLOWS_GOOGLE_DRIVE_MOCK",
    "supported": true,
    "resources": [
      "channels",
      "files"
    ]
  },
  {
    "provider": "granola",
    "namespace": "granola",
    "mockEnv": "RELAYFLOWS_GRANOLA_MOCK",
    "supported": true,
    "resources": [
      "folders",
      "notes"
    ]
  },
  {
    "provider": "hubspot",
    "namespace": "hubspot",
    "mockEnv": "RELAYFLOWS_HUBSPOT_MOCK",
    "supported": true,
    "resources": [
      "companies",
      "contacts",
      "deals",
      "tickets"
    ]
  },
  {
    "provider": "intercom",
    "namespace": "intercom",
    "mockEnv": "RELAYFLOWS_INTERCOM_MOCK",
    "supported": true,
    "resources": [
      "companies",
      "contacts",
      "conversations"
    ]
  },
  {
    "provider": "jira",
    "namespace": "jira",
    "mockEnv": "RELAYFLOWS_JIRA_MOCK",
    "supported": true,
    "resources": [
      "comments",
      "issues",
      "projects",
      "transitions"
    ]
  },
  {
    "provider": "linear",
    "namespace": "linear",
    "mockEnv": "RELAYFLOWS_LINEAR_MOCK",
    "supported": true,
    "resources": [
      "agent-activities",
      "comments",
      "issues",
      "labels",
      "project-issue-assignments",
      "projects"
    ]
  },
  {
    "provider": "mailgun",
    "namespace": "mailgun",
    "mockEnv": "RELAYFLOWS_MAILGUN_MOCK",
    "supported": true,
    "resources": [
      "lists",
      "members",
      "messages"
    ]
  },
  {
    "provider": "mixpanel",
    "namespace": "mixpanel",
    "mockEnv": "RELAYFLOWS_MIXPANEL_MOCK",
    "supported": true,
    "resources": [
      "cohorts",
      "events",
      "profiles"
    ]
  },
  {
    "provider": "neon",
    "namespace": "neon",
    "mockEnv": "RELAYFLOWS_NEON_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "notion",
    "namespace": "notion",
    "mockEnv": "RELAYFLOWS_NOTION_MOCK",
    "supported": true,
    "resources": [
      "comments",
      "content",
      "pages",
      "properties"
    ]
  },
  {
    "provider": "onedrive",
    "namespace": "onedrive",
    "mockEnv": "RELAYFLOWS_ONEDRIVE_MOCK",
    "supported": true,
    "resources": [
      "items",
      "subscriptions"
    ]
  },
  {
    "provider": "pipedrive",
    "namespace": "pipedrive",
    "mockEnv": "RELAYFLOWS_PIPEDRIVE_MOCK",
    "supported": true,
    "resources": [
      "activities",
      "deals",
      "organizations",
      "persons"
    ]
  },
  {
    "provider": "postgres",
    "namespace": "postgres",
    "mockEnv": "RELAYFLOWS_POSTGRES_MOCK",
    "supported": true,
    "resources": [
      "listeners",
      "rows"
    ]
  },
  {
    "provider": "posthog",
    "namespace": "posthog",
    "mockEnv": "RELAYFLOWS_POSTHOG_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "ramp",
    "namespace": "ramp",
    "mockEnv": "RELAYFLOWS_RAMP_MOCK",
    "supported": true,
    "resources": [
      "accounting-accounts",
      "accounting-fields",
      "bills",
      "business",
      "departments",
      "entities",
      "item-receipts",
      "locations",
      "merchants",
      "purchase-orders",
      "receipts",
      "reimbursements",
      "repayments",
      "spend-programs",
      "transactions",
      "transfers",
      "users",
      "vendor-agreements",
      "vendors"
    ]
  },
  {
    "provider": "recall",
    "namespace": "recall",
    "mockEnv": "RELAYFLOWS_RECALL_MOCK",
    "supported": true,
    "resources": [
      "recordings"
    ]
  },
  {
    "provider": "reddit",
    "namespace": "reddit",
    "mockEnv": "RELAYFLOWS_REDDIT_MOCK",
    "supported": true,
    "resources": [
      "posts",
      "subreddits"
    ]
  },
  {
    "provider": "redis",
    "namespace": "redis",
    "mockEnv": "RELAYFLOWS_REDIS_MOCK",
    "supported": true,
    "resources": [
      "keys",
      "listeners"
    ]
  },
  {
    "provider": "s3",
    "namespace": "s3",
    "mockEnv": "RELAYFLOWS_S3_MOCK",
    "supported": true,
    "resources": [
      "objects",
      "queues"
    ]
  },
  {
    "provider": "salesforce",
    "namespace": "salesforce",
    "mockEnv": "RELAYFLOWS_SALESFORCE_MOCK",
    "supported": true,
    "resources": [
      "accounts",
      "cases",
      "contacts",
      "leads",
      "opportunities"
    ]
  },
  {
    "provider": "segment",
    "namespace": "segment",
    "mockEnv": "RELAYFLOWS_SEGMENT_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "sendgrid",
    "namespace": "sendgrid",
    "mockEnv": "RELAYFLOWS_SENDGRID_MOCK",
    "supported": true,
    "resources": [
      "contacts",
      "mail"
    ]
  },
  {
    "provider": "sharepoint",
    "namespace": "sharepoint",
    "mockEnv": "RELAYFLOWS_SHAREPOINT_MOCK",
    "supported": true,
    "resources": [
      "items",
      "subscriptions"
    ]
  },
  {
    "provider": "shopify",
    "namespace": "shopify",
    "mockEnv": "RELAYFLOWS_SHOPIFY_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "shortcut",
    "namespace": "shortcut",
    "mockEnv": "RELAYFLOWS_SHORTCUT_MOCK",
    "supported": true,
    "resources": [
      "categories",
      "custom-fields",
      "epics",
      "groups",
      "iterations",
      "labels",
      "milestones",
      "projects",
      "stories"
    ]
  },
  {
    "provider": "slack",
    "namespace": "slack",
    "mockEnv": "RELAYFLOWS_SLACK_MOCK",
    "supported": true,
    "resources": [
      "direct-messages",
      "messages",
      "reactions",
      "replies"
    ]
  },
  {
    "provider": "stripe",
    "namespace": "stripe",
    "mockEnv": "RELAYFLOWS_STRIPE_MOCK",
    "supported": true,
    "resources": []
  },
  {
    "provider": "teams",
    "namespace": "teams",
    "mockEnv": "RELAYFLOWS_TEAMS_MOCK",
    "supported": true,
    "resources": [
      "messages",
      "replies"
    ]
  },
  {
    "provider": "telegram",
    "namespace": "telegram",
    "mockEnv": "RELAYFLOWS_TELEGRAM_MOCK",
    "supported": true,
    "resources": [
      "callback-queries",
      "commands",
      "inline-queries",
      "menu-button",
      "messages",
      "reactions"
    ]
  },
  {
    "provider": "webhook-server",
    "namespace": "webhookServer",
    "mockEnv": "RELAYFLOWS_WEBHOOK_SERVER_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "x",
    "namespace": "x",
    "mockEnv": "RELAYFLOWS_X_MOCK",
    "supported": false,
    "resources": []
  },
  {
    "provider": "zendesk",
    "namespace": "zendesk",
    "mockEnv": "RELAYFLOWS_ZENDESK_MOCK",
    "supported": true,
    "resources": [
      "comments",
      "tickets",
      "users"
    ]
  }
] as const;
