// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { rampClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type RampHelper = JournalHelper<ReturnType<typeof rampClient>>;

export const createRampHelper = (dispatch: EffectDispatcher): RampHelper =>
  bindHelper("ramp", rampClient, dispatch);
