// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { providerClient } from "@relayfile/relay-helpers";
import type { RelayClientOptions } from "@relayfile/relay-helpers/transport";
const rampClient = (options: RelayClientOptions) => providerClient("ramp", options);
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type RampHelper = JournalHelper<ReturnType<typeof rampClient>>;

export const createRampHelper = (dispatch: EffectDispatcher): RampHelper =>
  bindHelper("ramp", rampClient, dispatch);
