// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { recallClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type RecallHelper = JournalHelper<ReturnType<typeof recallClient>>;

export const createRecallHelper = (dispatch: EffectDispatcher): RecallHelper =>
  bindHelper("recall", recallClient, dispatch);
