// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { redditClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type RedditHelper = JournalHelper<ReturnType<typeof redditClient>>;

export const createRedditHelper = (dispatch: EffectDispatcher): RedditHelper =>
  bindHelper("reddit", redditClient, dispatch);
