// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { redisClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type RedisHelper = JournalHelper<ReturnType<typeof redisClient>>;

export const createRedisHelper = (dispatch: EffectDispatcher): RedisHelper =>
  bindHelper("redis", redisClient, dispatch);
