// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { s3Client } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type S3Helper = JournalHelper<ReturnType<typeof s3Client>>;

export const createS3Helper = (dispatch: EffectDispatcher): S3Helper =>
  bindHelper("s3", s3Client, dispatch);
