// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { salesforceClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type SalesforceHelper = JournalHelper<ReturnType<typeof salesforceClient>>;

export const createSalesforceHelper = (dispatch: EffectDispatcher): SalesforceHelper =>
  bindHelper("salesforce", salesforceClient, dispatch);
