// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { sendgridClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type SendgridHelper = JournalHelper<ReturnType<typeof sendgridClient>>;

export const createSendgridHelper = (dispatch: EffectDispatcher): SendgridHelper =>
  bindHelper("sendgrid", sendgridClient, dispatch);
