// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { sharepointClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type SharepointHelper = JournalHelper<ReturnType<typeof sharepointClient>>;

export const createSharepointHelper = (dispatch: EffectDispatcher): SharepointHelper =>
  bindHelper("sharepoint", sharepointClient, dispatch);
