// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { shortcutClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type ShortcutHelper = JournalHelper<ReturnType<typeof shortcutClient>>;

export const createShortcutHelper = (dispatch: EffectDispatcher): ShortcutHelper =>
  bindHelper("shortcut", shortcutClient, dispatch);
