// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import type { SlackHelper as RuntimeSlackHelper } from "../slack.js";

/** Adapter argument shapes over the journal-backed Slack dispatcher. */
export interface SlackHelper {
  post(channel: string, text: string, opts?: {
      replyTo?: string;
  }): ReturnType<RuntimeSlackHelper["post"]>;
  dm(user: string, text: string): ReturnType<RuntimeSlackHelper["dm"]>;
  reply(channel: string, threadTs: string, text: string): ReturnType<RuntimeSlackHelper["reply"]>;
  react(channel: string, messageTs: string, emoji: string): ReturnType<RuntimeSlackHelper["react"]>;
}
