// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { stripeClient } from "../helper-clients.js";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type StripeHelper = JournalHelper<ReturnType<typeof stripeClient>>;

export const createStripeHelper = (dispatch: EffectDispatcher): StripeHelper =>
  bindHelper("stripe", stripeClient, dispatch);
