// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { teamsClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type TeamsHelper = JournalHelper<ReturnType<typeof teamsClient>>;

export const createTeamsHelper = (dispatch: EffectDispatcher): TeamsHelper =>
  bindHelper("teams", teamsClient, dispatch);
