// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { telegramClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type TelegramHelper = JournalHelper<ReturnType<typeof telegramClient>>;

export const createTelegramHelper = (dispatch: EffectDispatcher): TelegramHelper =>
  bindHelper("telegram", telegramClient, dispatch);
