// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { bindHelper, type EffectDispatcher, type JournalHelper, type UnavailableHelper } from "../effect-transport.js";

export type XHelper = UnavailableHelper;

export const createXHelper = (dispatch: EffectDispatcher): XHelper =>
  bindHelper("x", undefined, dispatch);
