// GENERATED by scripts/generate-helpers.mjs — do not edit.
// Run `npm run gen --prefix packages/surface` from the repository root.

import { zendeskClient } from "@relayfile/relay-helpers";
import { bindHelper, type EffectDispatcher, type JournalHelper } from "../effect-transport.js";

export type ZendeskHelper = JournalHelper<ReturnType<typeof zendeskClient>>;

export const createZendeskHelper = (dispatch: EffectDispatcher): ZendeskHelper =>
  bindHelper("zendesk", zendeskClient, dispatch);
